/**
 * BLUELOCK // TRANSFER IQ - Comprehensive Mock Database
 * Realistic datasets for players, clubs, live transfers, and breaking news.
 * Featuring real, high-resolution local photography and official club crests.
 */

export const CLUBS = [
  {
    id: "real-madrid",
    name: "Real Madrid",
    shortName: "RMA",
    badge: "assets/clubs/real-madrid.png",
    color: "#00529F",
    accentColor: "#FEBE10",
    country: "Spain",
    flag: "🇪🇸",
    league: "La Liga",
    stadium: "Santiago Bernabéu (85,000)",
    squadValue: "€1.36B",
    transferBudget: "€160M",
    wageBill: "€280M/yr",
    president: "Florentino Pérez",
    manager: "Carlo Ancelotti",
    egoRank: "#1 Galactic Power",
    description: "The European football royalty with ruthless transfer precision and infinite galactic prestige.",
    incoming: [
      { player: "Kylian Mbappé", from: "Paris Saint-Germain", fee: "Free (€150M Sign-on)", status: "CONFIRMED" },
      { player: "Endrick", from: "Palmeiras", fee: "€47.5M", status: "CONFIRMED" },
      { player: "Alphonso Davies", from: "Bayern Munich", fee: "€45M (Negotiating)", status: "NEGOTIATING" }
    ],
    outgoing: [
      { player: "Toni Kroos", to: "Retired", fee: "—", status: "CONFIRMED" },
      { player: "Nacho Fernández", to: "Al Qadsiah", fee: "Free", status: "CONFIRMED" },
      { player: "Rodrygo", to: "Manchester City", fee: "€120M (Rumour)", status: "RUMOUR" }
    ],
    targets: [
      { playerId: "alphonso-davies", name: "Alphonso Davies", value: "€50M", interest: "VERY HIGH", status: "Advanced Bids" },
      { playerId: "florian-wirtz", name: "Florian Wirtz", value: "€130M", interest: "HIGH", status: "Scouting 2025" },
      { playerId: "rodri", name: "Rodri", value: "€130M", interest: "MEDIUM", status: "Initial Inquiries" }
    ]
  },
  {
    id: "man-city",
    name: "Manchester City",
    shortName: "MCI",
    badge: "assets/clubs/man-city.png",
    color: "#6CABDD",
    accentColor: "#1C2C5B",
    country: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    league: "Premier League",
    stadium: "Etihad Stadium (53,400)",
    squadValue: "€1.29B",
    transferBudget: "€185M",
    wageBill: "€260M/yr",
    president: "Khaldoon Al Mubarak",
    manager: "Pep Guardiola",
    egoRank: "#2 Tactical Dominance",
    description: "Reigning Premier League powerhouse driven by hyper-systemic possession and financial depth.",
    incoming: [
      { player: "Savinho", from: "Troyes", fee: "€40M", status: "CONFIRMED" },
      { player: "İlkay Gündoğan", from: "Barcelona", fee: "Free", status: "CONFIRMED" },
      { player: "Bruno Guimarães", from: "Newcastle", fee: "€115M (Target)", status: "NEGOTIATING" }
    ],
    outgoing: [
      { player: "Julián Álvarez", to: "Atlético Madrid", fee: "€95M", status: "CONFIRMED" },
      { player: "Kalvin Phillips", to: "Ipswich Town", fee: "Loan", status: "CONFIRMED" },
      { player: "Ederson", to: "Al-Ittihad", fee: "€50M (Rumour)", status: "RUMOUR" }
    ],
    targets: [
      { playerId: "bruno-guimaraes", name: "Bruno Guimarães", value: "€85M", interest: "VERY HIGH", status: "Release Clause Active" },
      { playerId: "jamal-musiala", name: "Jamal Musiala", value: "€130M", interest: "HIGH", status: "Monitoring Renewal" },
      { playerId: "joshua-kimmich", name: "Joshua Kimmich", value: "€50M", interest: "MEDIUM", status: "Contract Talks" }
    ]
  },
  {
    id: "barcelona",
    name: "FC Barcelona",
    shortName: "BAR",
    badge: "assets/clubs/barcelona.png",
    color: "#A50044",
    accentColor: "#004D98",
    country: "Spain",
    flag: "🇪🇸",
    league: "La Liga",
    stadium: "Spotify Camp Nou (105,000 renov.)",
    squadValue: "€945M",
    transferBudget: "€65M",
    wageBill: "€210M/yr",
    president: "Joan Laporta",
    manager: "Hansi Flick",
    egoRank: "#3 Youth Prodigy Forge",
    description: "Catalan masters undergoing aggressive tactical evolution powered by La Masia generational icons.",
    incoming: [
      { player: "Dani Olmo", from: "RB Leipzig", fee: "€55M + €7M", status: "CONFIRMED" },
      { player: "Pau Víctor", from: "Girona", fee: "€2.7M", status: "CONFIRMED" },
      { player: "Rafael Leão", from: "AC Milan", fee: "€90M (Rumour)", status: "RUMOUR" }
    ],
    outgoing: [
      { player: "İlkay Gündoğan", to: "Manchester City", fee: "Free", status: "CONFIRMED" },
      { player: "Vitor Roque", to: "Real Betis", fee: "Loan", status: "CONFIRMED" },
      { player: "Clément Lenglet", to: "Atlético Madrid", fee: "Loan", status: "CONFIRMED" }
    ],
    targets: [
      { playerId: "rafael-leao", name: "Rafael Leão", value: "€90M", interest: "HIGH", status: "Agent Inquiry" },
      { playerId: "joshua-kimmich", name: "Joshua Kimmich", value: "€50M", interest: "HIGH", status: "Flick Preference" },
      { playerId: "julian-alvarez", name: "Julián Álvarez", value: "€90M", interest: "LOW", status: "Priced Out" }
    ]
  },
  {
    id: "arsenal",
    name: "Arsenal FC",
    shortName: "ARS",
    badge: "assets/clubs/arsenal.png",
    color: "#EF0107",
    accentColor: "#063672",
    country: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    league: "Premier League",
    stadium: "Emirates Stadium (60,704)",
    squadValue: "€1.17B",
    transferBudget: "€95M",
    wageBill: "€205M/yr",
    president: "Stan Kroenke",
    manager: "Mikel Arteta",
    egoRank: "#4 Relentless Precision",
    description: "Young, high-intensity title challengers with ironclad defensive metrics and fluid attack.",
    incoming: [
      { player: "Riccardo Calafiori", from: "Bologna", fee: "€45M", status: "CONFIRMED" },
      { player: "Mikel Merino", from: "Real Sociedad", fee: "€32M", status: "CONFIRMED" },
      { player: "Victor Osimhen", from: "Napoli", fee: "€110M (Bid)", status: "NEGOTIATING" }
    ],
    outgoing: [
      { player: "Emile Smith Rowe", to: "Fulham", fee: "€32M", status: "CONFIRMED" },
      { player: "Eddie Nketiah", to: "Crystal Palace", fee: "€30M", status: "CONFIRMED" },
      { player: "Aaron Ramsdale", to: "Southampton", fee: "€21M", status: "CONFIRMED" }
    ],
    targets: [
      { playerId: "victor-osimhen", name: "Victor Osimhen", value: "€100M", interest: "VERY HIGH", status: "Negotiating Terms" },
      { playerId: "alexander-isak", name: "Alexander Isak", value: "€75M", interest: "HIGH", status: "Long-term Target" },
      { playerId: "florian-wirtz", name: "Florian Wirtz", value: "€130M", interest: "MEDIUM", status: "Valuation Check" }
    ]
  },
  {
    id: "bayern-munich",
    name: "Bayern Munich",
    shortName: "BAY",
    badge: "assets/clubs/bayern.png",
    color: "#DC052D",
    accentColor: "#0066B2",
    country: "Germany",
    flag: "🇩🇪",
    league: "Bundesliga",
    stadium: "Allianz Arena (75,000)",
    squadValue: "€960M",
    transferBudget: "€110M",
    wageBill: "€240M/yr",
    president: "Herbert Hainer",
    manager: "Vincent Kompany",
    egoRank: "#5 Bavarian Titan",
    description: "German juggernaut restructuring under dynamic tactical pressure and elite squad depth.",
    incoming: [
      { player: "Michael Olise", from: "Crystal Palace", fee: "€53M", status: "CONFIRMED" },
      { player: "João Palhinha", from: "Fulham", fee: "€51M", status: "CONFIRMED" },
      { player: "Hiroki Ito", from: "Stuttgart", fee: "€23.5M", status: "CONFIRMED" }
    ],
    outgoing: [
      { player: "Matthijs de Ligt", to: "Manchester United", fee: "€45M", status: "CONFIRMED" },
      { player: "Noussair Mazraoui", to: "Manchester United", fee: "€15M", status: "CONFIRMED" },
      { player: "Alphonso Davies", to: "Real Madrid", fee: "€45M", status: "NEGOTIATING" }
    ],
    targets: [
      { playerId: "florian-wirtz", name: "Florian Wirtz", value: "€130M", interest: "EXTREME", status: "Top 2025 Priority" },
      { playerId: "rafael-leao", name: "Rafael Leão", value: "€90M", interest: "MEDIUM", status: "Contingency Plan" }
    ]
  },
  {
    id: "psg",
    name: "Paris Saint-Germain",
    shortName: "PSG",
    badge: "assets/clubs/psg.png",
    color: "#004170",
    accentColor: "#DA291C",
    country: "France",
    flag: "🇫🇷",
    league: "Ligue 1",
    stadium: "Parc des Princes (48,583)",
    squadValue: "€890M",
    transferBudget: "€210M",
    wageBill: "€290M/yr",
    president: "Nasser Al-Khelaifi",
    manager: "Luis Enrique",
    egoRank: "#6 Collective Blitz",
    description: "Transitioning from individual galácticos to a terrifying high-press collective scouting machine.",
    incoming: [
      { player: "João Neves", from: "Benfica", fee: "€60M + €10M", status: "CONFIRMED" },
      { player: "Willian Pacho", from: "Eintracht Frankfurt", fee: "€40M", status: "CONFIRMED" },
      { player: "Désiré Doué", from: "Rennes", fee: "€50M", status: "CONFIRMED" }
    ],
    outgoing: [
      { player: "Kylian Mbappé", to: "Real Madrid", fee: "Free", status: "CONFIRMED" },
      { player: "Manuel Ugarte", to: "Manchester United", fee: "€50M", status: "CONFIRMED" },
      { player: "Keylor Navas", to: "Free Agent", fee: "Free", status: "CONFIRMED" }
    ],
    targets: [
      { playerId: "victor-osimhen", name: "Victor Osimhen", value: "€100M", interest: "VERY HIGH", status: "Personal Terms Agreed" },
      { playerId: "bruno-guimaraes", name: "Bruno Guimarães", value: "€85M", interest: "HIGH", status: "Ongoing Inquiries" }
    ]
  },
  {
    id: "liverpool",
    name: "Liverpool FC",
    shortName: "LIV",
    badge: "assets/clubs/liverpool.png",
    color: "#C8102E",
    accentColor: "#00B2A9",
    country: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    league: "Premier League",
    stadium: "Anfield (61,276)",
    squadValue: "€930M",
    transferBudget: "€120M",
    wageBill: "€215M/yr",
    president: "Tom Werner",
    manager: "Arne Slot",
    egoRank: "#7 Red Heavy Metal",
    description: "Statistical ruthlessness, high pressing efficiency, and clinical transition mastery.",
    incoming: [
      { player: "Federico Chiesa", from: "Juventus", fee: "€15M", status: "CONFIRMED" },
      { player: "Giorgi Mamardashvili", from: "Valencia", fee: "€30M (2025)", status: "CONFIRMED" },
      { player: "Alexander Isak", from: "Newcastle", fee: "€95M (Inquiry)", status: "RUMOUR" }
    ],
    outgoing: [
      { player: "Fabio Carvalho", to: "Brentford", fee: "€23.4M", status: "CONFIRMED" },
      { player: "Sepp van den Berg", to: "Brentford", fee: "€23.6M", status: "CONFIRMED" },
      { player: "Joel Matip", to: "Free Agent", fee: "Free", status: "CONFIRMED" }
    ],
    targets: [
      { playerId: "alexander-isak", name: "Alexander Isak", value: "€75M", interest: "HIGH", status: "Target Evaluated" },
      { playerId: "joshua-kimmich", name: "Joshua Kimmich", value: "€50M", interest: "MEDIUM", status: "Scouting Situation" }
    ]
  },
  {
    id: "chelsea",
    name: "Chelsea FC",
    shortName: "CHE",
    badge: "assets/clubs/chelsea.png",
    color: "#034694",
    accentColor: "#EE242C",
    country: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    league: "Premier League",
    stadium: "Stamford Bridge (40,341)",
    squadValue: "€980M",
    transferBudget: "€135M",
    wageBill: "€225M/yr",
    president: "Todd Boehly",
    manager: "Enzo Maresca",
    egoRank: "#8 Hyper-Accumulator",
    description: "Aggressive multi-million long-term contract structure hoovering global wonderkids.",
    incoming: [
      { player: "Pedro Neto", from: "Wolves", fee: "€60M + €3M", status: "CONFIRMED" },
      { player: "João Félix", from: "Atlético Madrid", fee: "€52M", status: "CONFIRMED" },
      { player: "Kiernan Dewsbury-Hall", from: "Leicester", fee: "€35M", status: "CONFIRMED" }
    ],
    outgoing: [
      { player: "Conor Gallagher", to: "Atlético Madrid", fee: "€42M", status: "CONFIRMED" },
      { player: "Romelu Lukaku", to: "Napoli", fee: "€30M", status: "CONFIRMED" },
      { player: "Raheem Sterling", to: "Arsenal", fee: "Loan", status: "CONFIRMED" }
    ],
    targets: [
      { playerId: "victor-osimhen", name: "Victor Osimhen", value: "€100M", interest: "VERY HIGH", status: "Direct Club Talks" },
      { playerId: "rafael-leao", name: "Rafael Leão", value: "€90M", interest: "MEDIUM", status: "Financial Assessment" }
    ]
  },
  {
    id: "atletico-madrid",
    name: "Atlético Madrid",
    shortName: "ATM",
    badge: "assets/clubs/atletico.png",
    color: "#CB3524",
    accentColor: "#272E61",
    country: "Spain",
    flag: "🇪🇸",
    league: "La Liga",
    stadium: "Riyadh Air Metropolitano (70,460)",
    squadValue: "€530M",
    transferBudget: "€45M",
    wageBill: "€145M/yr",
    president: "Enrique Cerezo",
    manager: "Diego Simeone",
    egoRank: "#9 Iron Fortress",
    description: "Fierce combative identity backed by massive frontline squad overhaul.",
    incoming: [
      { player: "Julián Álvarez", from: "Manchester City", fee: "€75M + €20M", status: "CONFIRMED" },
      { player: "Conor Gallagher", from: "Chelsea", fee: "€42M", status: "CONFIRMED" },
      { player: "Robin Le Normand", from: "Real Sociedad", fee: "€34.5M", status: "CONFIRMED" },
      { player: "Alexander Sørloth", from: "Villarreal", fee: "€32M", status: "CONFIRMED" }
    ],
    outgoing: [
      { player: "João Félix", to: "Chelsea", fee: "€52M", status: "CONFIRMED" },
      { player: "Álvaro Morata", to: "AC Milan", fee: "€13M", status: "CONFIRMED" },
      { player: "Memphis Depay", to: "Corinthians", fee: "Free", status: "CONFIRMED" }
    ],
    targets: [
      { playerId: "bruno-guimaraes", name: "Bruno Guimarães", value: "€85M", interest: "MEDIUM", status: "Monitored" }
    ]
  },
  {
    id: "inter-milan",
    name: "Inter Milan",
    shortName: "INT",
    badge: "assets/clubs/inter.png",
    color: "#010E80",
    accentColor: "#0066B2",
    country: "Italy",
    flag: "🇮🇹",
    league: "Serie A",
    stadium: "San Siro (75,923)",
    squadValue: "€670M",
    transferBudget: "€55M",
    wageBill: "€150M/yr",
    president: "Giuseppe Marotta",
    manager: "Simone Inzaghi",
    egoRank: "#10 Tactical Mastermind",
    description: "The kings of free transfers and ruthlessly synced 3-5-2 vertical attacking machines.",
    incoming: [
      { player: "Piotr Zieliński", from: "Napoli", fee: "Free", status: "CONFIRMED" },
      { player: "Mehdi Taremi", from: "Porto", fee: "Free", status: "CONFIRMED" },
      { player: "Josep Martínez", from: "Genoa", fee: "€13.5M", status: "CONFIRMED" }
    ],
    outgoing: [
      { player: "Alexis Sánchez", to: "Udinese", fee: "Free", status: "CONFIRMED" },
      { player: "Davy Klaassen", to: "Ajax", fee: "Free", status: "CONFIRMED" }
    ],
    targets: [
      { playerId: "joshua-kimmich", name: "Joshua Kimmich", value: "€50M", interest: "HIGH", status: "Free Agent 2025 Inquiry" }
    ]
  }
];

export const PLAYERS = [
  {
    id: "kylian-mbappe",
    name: "Kylian Mbappé",
    image: "assets/players/mbappe.jpg",
    photo: "assets/players/mbappe.jpg",
    nationality: "France",
    flag: "🇫🇷",
    age: 25,
    position: "Forward (LW / ST)",
    currentClubId: "real-madrid",
    currentClub: "Real Madrid",
    targetClubId: "psg",
    targetClub: "Paris Saint-Germain (Previous)",
    shirtNumber: 9,
    preferredFoot: "Right",
    contractExpiry: "2029-06-30",
    marketValueRaw: 180,
    marketValue: "€180M",
    askingPrice: "€200M",
    reportedOffer: "€150M Sign-on Bonus",
    valueDiff: "+€0M (Peak Valuation)",
    transferType: "Free Transfer (Completed)",
    transferStatus: "CONFIRMED",
    probability: 100,
    confidence: 100,
    egoRating: 99,
    strikerIndex: 98,
    marketThreat: "SUPREME",
    momentum: 99,
    rating: 93,
    overview: "Generational speed and ruthless finishing weapon. Crown jewel of European football and world cup winner.",
    stats: {
      appearances: 48,
      goals: 44,
      assists: 10,
      minutes: 4120,
      xg: 38.6,
      xa: 8.9,
      shots: 184,
      keyPasses: 68,
      dribbles: 142,
      passAccuracy: 84.5,
      tackles: 14,
      interceptions: 8
    },
    radar: {
      pace: 97,
      shooting: 93,
      passing: 84,
      dribbling: 94,
      defending: 36,
      physical: 79,
      ego: 99
    },
    valueHistory: [
      { year: "2020", value: 160 },
      { year: "2021", value: 160 },
      { year: "2022", value: 170 },
      { year: "2023", value: 180 },
      { year: "2024", value: 180 }
    ],
    interestedClubs: [
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "MAXIMUM", offer: "€150M Package", status: "Signed & Presented", probability: 100 },
      { clubId: "liverpool", name: "Liverpool", league: "Premier League", interest: "EXTINCT", offer: "Historic Inquiry", status: "Rejected", probability: 0 }
    ]
  },
  {
    id: "erling-haaland",
    name: "Erling Haaland",
    image: "assets/players/haaland.jpg",
    photo: "assets/players/haaland.jpg",
    nationality: "Norway",
    flag: "🇳🇴",
    age: 24,
    position: "Striker (ST)",
    currentClubId: "man-city",
    currentClub: "Manchester City",
    targetClubId: "real-madrid",
    targetClub: "Real Madrid",
    shirtNumber: 9,
    preferredFoot: "Left",
    contractExpiry: "2027-06-30",
    marketValueRaw: 180,
    marketValue: "€180M",
    askingPrice: "€220M (Release Clause)",
    reportedOffer: "€200M Projected",
    valueDiff: "+€20M",
    transferType: "Permanent",
    transferStatus: "RUMOUR",
    probability: 32,
    confidence: 45,
    egoRating: 98,
    strikerIndex: 99,
    marketThreat: "SUPREME",
    momentum: 88,
    rating: 92,
    overview: "Cybernetic goal-scoring powerhouse. Unprecedented box efficiency and physical dominance.",
    stats: {
      appearances: 45,
      goals: 48,
      assists: 6,
      minutes: 3880,
      xg: 42.1,
      xa: 4.8,
      shots: 168,
      keyPasses: 34,
      dribbles: 38,
      passAccuracy: 76.2,
      tackles: 12,
      interceptions: 6
    },
    radar: {
      pace: 89,
      shooting: 96,
      passing: 69,
      dribbling: 81,
      defending: 42,
      physical: 92,
      ego: 98
    },
    valueHistory: [
      { year: "2020", value: 100 },
      { year: "2021", value: 130 },
      { year: "2022", value: 150 },
      { year: "2023", value: 180 },
      { year: "2024", value: 180 }
    ],
    interestedClubs: [
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "HIGH", offer: "€200M (Clause Monitor)", status: "Long-term Target 2026", probability: 35 },
      { clubId: "barcelona", name: "Barcelona", league: "La Liga", interest: "MEDIUM", offer: "Dream Project", status: "Financial Assessment", probability: 18 }
    ]
  },
  {
    id: "jude-bellingham",
    name: "Jude Bellingham",
    image: "assets/players/bellingham.jpg",
    photo: "assets/players/bellingham.jpg",
    nationality: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    age: 21,
    position: "Attacking Midfielder (CAM / CM)",
    currentClubId: "real-madrid",
    currentClub: "Real Madrid",
    targetClubId: "man-city",
    targetClub: "Manchester City",
    shirtNumber: 5,
    preferredFoot: "Right",
    contractExpiry: "2029-06-30",
    marketValueRaw: 180,
    marketValue: "€180M",
    askingPrice: "Untouchable",
    reportedOffer: "€220M Inquiry",
    valueDiff: "+€0M",
    transferType: "Contract Renewal Protected",
    transferStatus: "CONFIRMED",
    probability: 2,
    confidence: 99,
    egoRating: 97,
    strikerIndex: 91,
    marketThreat: "SUPREME",
    momentum: 94,
    rating: 92,
    overview: "Total midfielder, box-to-box dominance, clutch goals, and magnetic midfield charisma.",
    stats: {
      appearances: 42,
      goals: 23,
      assists: 13,
      minutes: 3640,
      xg: 18.5,
      xa: 9.7,
      shots: 104,
      keyPasses: 74,
      dribbles: 92,
      passAccuracy: 88.6,
      tackles: 58,
      interceptions: 34
    },
    radar: {
      pace: 82,
      shooting: 88,
      passing: 88,
      dribbling: 90,
      defending: 76,
      physical: 86,
      ego: 97
    },
    valueHistory: [
      { year: "2020", value: 27 },
      { year: "2021", value: 55 },
      { year: "2022", value: 90 },
      { year: "2023", value: 120 },
      { year: "2024", value: 180 }
    ],
    interestedClubs: [
      { clubId: "man-city", name: "Manchester City", league: "Premier League", interest: "HIGH", offer: "Record Bid Rejected", status: "Untouchable", probability: 2 }
    ]
  },
  {
    id: "vinicius-jr",
    name: "Vinícius Júnior",
    image: "assets/players/vinicius.jpg",
    photo: "assets/players/vinicius.jpg",
    nationality: "Brazil",
    flag: "🇧🇷",
    age: 24,
    position: "Left Winger (LW)",
    currentClubId: "real-madrid",
    currentClub: "Real Madrid",
    targetClubId: "psg",
    targetClub: "Saudi PIF / PSG",
    shirtNumber: 7,
    preferredFoot: "Right",
    contractExpiry: "2027-06-30",
    marketValueRaw: 180,
    marketValue: "€180M",
    askingPrice: "€1.0B (Release Clause)",
    reportedOffer: "€400M Mega Offer Rumour",
    valueDiff: "+€30M",
    transferType: "Contract Extension Talks",
    transferStatus: "RUMOUR",
    probability: 14,
    confidence: 50,
    egoRating: 98,
    strikerIndex: 94,
    marketThreat: "SUPREME",
    momentum: 96,
    rating: 92,
    overview: "Ballon d'Or tier electrifying dribbler with devastating Champions League clutch pedigree.",
    stats: {
      appearances: 39,
      goals: 24,
      assists: 11,
      minutes: 3280,
      xg: 20.2,
      xa: 10.4,
      shots: 118,
      keyPasses: 82,
      dribbles: 164,
      passAccuracy: 81.4,
      tackles: 26,
      interceptions: 12
    },
    radar: {
      pace: 96,
      shooting: 89,
      passing: 83,
      dribbling: 96,
      defending: 32,
      physical: 74,
      ego: 98
    },
    valueHistory: [
      { year: "2020", value: 50 },
      { year: "2021", value: 60 },
      { year: "2022", value: 120 },
      { year: "2023", value: 150 },
      { year: "2024", value: 180 }
    ],
    interestedClubs: [
      { clubId: "psg", name: "Paris Saint-Germain", league: "Ligue 1", interest: "HIGH", offer: "€250M Inquiry", status: "Rejected immediately", probability: 8 },
      { clubId: "chelsea", name: "Chelsea", league: "Premier League", interest: "MEDIUM", offer: "Monitoring", status: "Exploratory", probability: 5 }
    ]
  },
  {
    id: "lamine-yamal",
    name: "Lamine Yamal",
    image: "assets/players/yamal.jpg",
    photo: "assets/players/yamal.jpg",
    nationality: "Spain",
    flag: "🇪🇸",
    age: 17,
    position: "Right Winger (RW)",
    currentClubId: "barcelona",
    currentClub: "FC Barcelona",
    targetClubId: "psg",
    targetClub: "Paris Saint-Germain",
    shirtNumber: 19,
    preferredFoot: "Left",
    contractExpiry: "2026-06-30",
    marketValueRaw: 150,
    marketValue: "€150M",
    askingPrice: "€1.0B (Clause)",
    reportedOffer: "€200M (Turned Down)",
    valueDiff: "+€60M (Skyrocketing)",
    transferType: "Contract Extension",
    transferStatus: "NEGOTIATING",
    probability: 12,
    confidence: 88,
    egoRating: 96,
    strikerIndex: 90,
    marketThreat: "CRITICAL",
    momentum: 99,
    rating: 89,
    overview: "Generational prodigy. Euro 2024 MVP revelation with world-shattering dribbling & vision at age 17.",
    stats: {
      appearances: 50,
      goals: 12,
      assists: 18,
      minutes: 3820,
      xg: 11.4,
      xa: 16.2,
      shots: 96,
      keyPasses: 104,
      dribbles: 172,
      passAccuracy: 83.8,
      tackles: 42,
      interceptions: 18
    },
    radar: {
      pace: 91,
      shooting: 83,
      passing: 89,
      dribbling: 95,
      defending: 40,
      physical: 66,
      ego: 96
    },
    valueHistory: [
      { year: "2023", value: 25 },
      { year: "2023.5", value: 50 },
      { year: "2024.1", value: 90 },
      { year: "2024.5", value: 120 },
      { year: "2024.8", value: 150 }
    ],
    interestedClubs: [
      { clubId: "psg", name: "Paris Saint-Germain", league: "Ligue 1", interest: "VERY HIGH", offer: "€200M Bid", status: "Rejected by Laporta", probability: 10 }
    ]
  },
  {
    id: "florian-wirtz",
    name: "Florian Wirtz",
    image: "assets/players/wirtz.jpg",
    photo: "assets/players/wirtz.jpg",
    nationality: "Germany",
    flag: "🇩🇪",
    age: 21,
    position: "Attacking Midfielder / Playmaker",
    currentClubId: "bayern-munich",
    currentClub: "Bayer Leverkusen",
    targetClubId: "real-madrid",
    targetClub: "Real Madrid / Bayern Munich",
    shirtNumber: 10,
    preferredFoot: "Right",
    contractExpiry: "2027-06-30",
    marketValueRaw: 130,
    marketValue: "€130M",
    askingPrice: "€150M",
    reportedOffer: "€125M Bids Expected 2025",
    valueDiff: "+€25M",
    transferType: "Permanent (2025 Battle)",
    transferStatus: "NEGOTIATING",
    probability: 72,
    confidence: 84,
    egoRating: 95,
    strikerIndex: 90,
    marketThreat: "CRITICAL",
    momentum: 93,
    rating: 91,
    overview: "Maestro playmaker whose vision, half-turn acceleration, and spatial IQ powered Leverkusen's unbeaten double.",
    stats: {
      appearances: 49,
      goals: 18,
      assists: 20,
      minutes: 3950,
      xg: 15.2,
      xa: 18.9,
      shots: 112,
      keyPasses: 126,
      dribbles: 134,
      passAccuracy: 87.2,
      tackles: 44,
      interceptions: 22
    },
    radar: {
      pace: 84,
      shooting: 86,
      passing: 93,
      dribbling: 92,
      defending: 52,
      physical: 72,
      ego: 95
    },
    valueHistory: [
      { year: "2021", value: 45 },
      { year: "2022", value: 70 },
      { year: "2023", value: 85 },
      { year: "2023.5", value: 100 },
      { year: "2024", value: 130 }
    ],
    interestedClubs: [
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "VERY HIGH", offer: "€130M Plan", status: "Priority 2025 Target", probability: 65 },
      { clubId: "bayern-munich", name: "Bayern Munich", league: "Bundesliga", interest: "EXTREME", offer: "€140M Package", status: "Contact with Family", probability: 58 },
      { clubId: "man-city", name: "Manchester City", league: "Premier League", interest: "HIGH", offer: "€135M", status: "Pep Long-Term Wish", probability: 40 }
    ]
  },
  {
    id: "jamal-musiala",
    name: "Jamal Musiala",
    image: "assets/players/musiala.jpg",
    photo: "assets/players/musiala.jpg",
    nationality: "Germany",
    flag: "🇩🇪",
    age: 21,
    position: "Attacking Midfielder / Winger",
    currentClubId: "bayern-munich",
    currentClub: "Bayern Munich",
    targetClubId: "man-city",
    targetClub: "Manchester City",
    shirtNumber: 42,
    preferredFoot: "Right",
    contractExpiry: "2026-06-30",
    marketValueRaw: 130,
    marketValue: "€130M",
    askingPrice: "€160M / New Record Contract",
    reportedOffer: "€120M Inquiries",
    valueDiff: "+€20M",
    transferType: "Contract Extension Battle",
    transferStatus: "NEGOTIATING",
    probability: 54,
    confidence: 76,
    egoRating: 95,
    strikerIndex: 89,
    marketThreat: "CRITICAL",
    momentum: 91,
    rating: 91,
    overview: "Snake-like dribbling in congested penalty boxes with sublime balance and technical improvisation.",
    stats: {
      appearances: 40,
      goals: 15,
      assists: 12,
      minutes: 3120,
      xg: 13.8,
      xa: 9.4,
      shots: 88,
      keyPasses: 84,
      dribbles: 156,
      passAccuracy: 86.8,
      tackles: 36,
      interceptions: 19
    },
    radar: {
      pace: 88,
      shooting: 85,
      passing: 87,
      dribbling: 96,
      defending: 46,
      physical: 70,
      ego: 95
    },
    valueHistory: [
      { year: "2021", value: 38 },
      { year: "2022", value: 65 },
      { year: "2023", value: 100 },
      { year: "2023.5", value: 110 },
      { year: "2024", value: 130 }
    ],
    interestedClubs: [
      { clubId: "man-city", name: "Manchester City", league: "Premier League", interest: "VERY HIGH", offer: "€130M Bid Ready", status: "Watching Contract Talks", probability: 52 },
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "HIGH", offer: "Monitoring", status: "Bellingham Connection", probability: 35 }
    ]
  },
  {
    id: "rodri",
    name: "Rodri",
    image: "assets/players/rodri.jpg",
    photo: "assets/players/rodri.jpg",
    nationality: "Spain",
    flag: "🇪🇸",
    age: 28,
    position: "Defensive Midfielder (CDM)",
    currentClubId: "man-city",
    currentClub: "Manchester City",
    targetClubId: "real-madrid",
    targetClub: "Real Madrid",
    shirtNumber: 16,
    preferredFoot: "Right",
    contractExpiry: "2027-06-30",
    marketValueRaw: 130,
    marketValue: "€130M",
    askingPrice: "€150M",
    reportedOffer: "€115M Exploration",
    valueDiff: "+€10M",
    transferType: "Contract Extension",
    transferStatus: "RUMOUR",
    probability: 25,
    confidence: 62,
    egoRating: 96,
    strikerIndex: 82,
    marketThreat: "HIGH",
    momentum: 89,
    rating: 93,
    overview: "Ballon d'Or winning midfielder. The undisputed anchor and master conductor of modern football tempo.",
    stats: {
      appearances: 50,
      goals: 9,
      assists: 14,
      minutes: 4320,
      xg: 6.8,
      xa: 11.2,
      shots: 62,
      keyPasses: 88,
      dribbles: 52,
      passAccuracy: 93.4,
      tackles: 104,
      interceptions: 68
    },
    radar: {
      pace: 72,
      shooting: 82,
      passing: 92,
      dribbling: 84,
      defending: 91,
      physical: 89,
      ego: 96
    },
    valueHistory: [
      { year: "2020", value: 64 },
      { year: "2021", value: 70 },
      { year: "2022", value: 80 },
      { year: "2023", value: 100 },
      { year: "2024", value: 130 }
    ],
    interestedClubs: [
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "HIGH", offer: "€120M Assessment", status: "Spanish Core Vision", probability: 28 }
    ]
  },
  {
    id: "julian-alvarez",
    name: "Julián Álvarez",
    image: "assets/players/alvarez.jpg",
    photo: "assets/players/alvarez.jpg",
    nationality: "Argentina",
    flag: "🇦🇷",
    age: 24,
    position: "Forward (ST / SS)",
    currentClubId: "atletico-madrid",
    currentClub: "Atlético Madrid",
    targetClubId: "barcelona",
    targetClub: "FC Barcelona",
    shirtNumber: 19,
    preferredFoot: "Right",
    contractExpiry: "2030-06-30",
    marketValueRaw: 90,
    marketValue: "€90M",
    askingPrice: "€100M",
    reportedOffer: "€90M (€75M + €15M add-ons)",
    valueDiff: "+€5M",
    transferType: "Permanent",
    transferStatus: "NEGOTIATING",
    probability: 78,
    confidence: 85,
    egoRating: 92,
    strikerIndex: 93,
    marketThreat: "VERY HIGH",
    momentum: 92,
    rating: 88,
    overview: "World Cup & Champions League winning predator. Infinite pressing stamina and venomous finishing angles.",
    stats: {
      appearances: 54,
      goals: 21,
      assists: 13,
      minutes: 3680,
      xg: 19.8,
      xa: 11.2,
      shots: 124,
      keyPasses: 78,
      dribbles: 68,
      passAccuracy: 84.1,
      tackles: 52,
      interceptions: 24
    },
    radar: {
      pace: 86,
      shooting: 89,
      passing: 84,
      dribbling: 87,
      defending: 58,
      physical: 81,
      ego: 92
    },
    valueHistory: [
      { year: "2021", value: 20 },
      { year: "2022", value: 32 },
      { year: "2023", value: 60 },
      { year: "2023.5", value: 80 },
      { year: "2024", value: 90 }
    ],
    interestedClubs: [
      { clubId: "barcelona", name: "FC Barcelona", league: "La Liga", interest: "VERY HIGH", offer: "€90M Bid Formula", status: "Negotiating Terms", probability: 78 },
      { clubId: "psg", name: "Paris Saint-Germain", league: "Ligue 1", interest: "HIGH", offer: "€85M Initial Bid", status: "Monitoring", probability: 48 },
      { clubId: "chelsea", name: "Chelsea", league: "Premier League", interest: "MEDIUM", offer: "€80M Inquiry", status: "Evaluating", probability: 35 }
    ]
  },
  {
    id: "victor-osimhen",
    name: "Victor Osimhen",
    image: "assets/players/osimhen.jpg",
    photo: "assets/players/osimhen.jpg",
    nationality: "Nigeria",
    flag: "🇳🇬",
    age: 25,
    position: "Striker (ST)",
    currentClubId: "chelsea",
    currentClub: "Galatasaray (Loan from Napoli)",
    targetClubId: "arsenal",
    targetClub: "Arsenal / Chelsea / PSG",
    shirtNumber: 45,
    preferredFoot: "Right",
    contractExpiry: "2026-06-30",
    marketValueRaw: 100,
    marketValue: "€100M",
    askingPrice: "€115M (Break Clause)",
    reportedOffer: "€85M + Add-ons",
    valueDiff: "-€10M (Contract pressure)",
    transferType: "Loan with Option / Permanent",
    transferStatus: "NEGOTIATING",
    probability: 84,
    confidence: 90,
    egoRating: 96,
    strikerIndex: 97,
    marketThreat: "EXTREME",
    momentum: 95,
    rating: 89,
    overview: "Raw athletic beast with supersonic leap and devastating direct vertical threat.",
    stats: {
      appearances: 32,
      goals: 22,
      assists: 5,
      minutes: 2680,
      xg: 20.4,
      xa: 3.9,
      shots: 110,
      keyPasses: 32,
      dribbles: 48,
      passAccuracy: 74.0,
      tackles: 18,
      interceptions: 7
    },
    radar: {
      pace: 90,
      shooting: 91,
      passing: 68,
      dribbling: 82,
      defending: 38,
      physical: 88,
      ego: 96
    },
    valueHistory: [
      { year: "2020", value: 50 },
      { year: "2021", value: 60 },
      { year: "2022", value: 70 },
      { year: "2023", value: 120 },
      { year: "2024", value: 100 }
    ],
    interestedClubs: [
      { clubId: "arsenal", name: "Arsenal", league: "Premier League", interest: "VERY HIGH", offer: "€90M Bid", status: "Advanced Bids", probability: 82 },
      { clubId: "chelsea", name: "Chelsea", league: "Premier League", interest: "VERY HIGH", offer: "€85M + Wage Offer", status: "Direct Club Talks", probability: 79 },
      { clubId: "psg", name: "Paris Saint-Germain", league: "Ligue 1", interest: "HIGH", offer: "€95M Clause", status: "Negotiating", probability: 64 }
    ]
  },
  {
    id: "alexander-isak",
    name: "Alexander Isak",
    image: "assets/players/isak.jpg",
    photo: "assets/players/isak.jpg",
    nationality: "Sweden",
    flag: "🇸🇪",
    age: 24,
    position: "Striker / Winger (ST / LW)",
    currentClubId: "arsenal",
    currentClub: "Newcastle United",
    targetClubId: "arsenal",
    targetClub: "Arsenal FC",
    shirtNumber: 14,
    preferredFoot: "Right",
    contractExpiry: "2028-06-30",
    marketValueRaw: 75,
    marketValue: "€75M",
    askingPrice: "€110M",
    reportedOffer: "€95M",
    valueDiff: "+€20M",
    transferType: "Permanent",
    transferStatus: "RUMOUR",
    probability: 60,
    confidence: 72,
    egoRating: 93,
    strikerIndex: 95,
    marketThreat: "VERY HIGH",
    momentum: 86,
    rating: 87,
    overview: "Silky tall center-forward with Henry-esque finesse, lightning bursts, and deceptive balance.",
    stats: {
      appearances: 40,
      goals: 25,
      assists: 4,
      minutes: 3200,
      xg: 22.8,
      xa: 3.5,
      shots: 98,
      keyPasses: 46,
      dribbles: 82,
      passAccuracy: 80.2,
      tackles: 19,
      interceptions: 9
    },
    radar: {
      pace: 89,
      shooting: 89,
      passing: 77,
      dribbling: 88,
      defending: 35,
      physical: 76,
      ego: 93
    },
    valueHistory: [
      { year: "2021", value: 40 },
      { year: "2022", value: 50 },
      { year: "2023", value: 65 },
      { year: "2024", value: 75 }
    ],
    interestedClubs: [
      { clubId: "arsenal", name: "Arsenal", league: "Premier League", interest: "VERY HIGH", offer: "€95M Offer", status: "Arteta Target #1", probability: 64 },
      { clubId: "liverpool", name: "Liverpool", league: "Premier League", interest: "MEDIUM", offer: "€85M Inquiry", status: "Monitoring", probability: 42 }
    ]
  },
  {
    id: "alphonso-davies",
    name: "Alphonso Davies",
    image: "assets/players/davies.jpg",
    photo: "assets/players/davies.jpg",
    nationality: "Canada",
    flag: "🇨🇦",
    age: 23,
    position: "Left Back (LB / LWB)",
    currentClubId: "bayern-munich",
    currentClub: "Bayern Munich",
    targetClubId: "real-madrid",
    targetClub: "Real Madrid",
    shirtNumber: 19,
    preferredFoot: "Left",
    contractExpiry: "2025-06-30",
    marketValueRaw: 50,
    marketValue: "€50M",
    askingPrice: "€50M / Free 2025",
    reportedOffer: "€35M + €10M add-ons",
    valueDiff: "+€0M (Expiring Contract)",
    transferType: "Permanent / Free 2025 Pre-contract",
    transferStatus: "NEGOTIATING",
    probability: 88,
    confidence: 94,
    egoRating: 91,
    strikerIndex: 78,
    marketThreat: "HIGH",
    momentum: 93,
    rating: 87,
    overview: "Roadrunner turbo wing-back with game-breaking recovery speed and vertical offensive transitions.",
    stats: {
      appearances: 42,
      goals: 3,
      assists: 8,
      minutes: 3410,
      xg: 2.1,
      xa: 7.4,
      shots: 38,
      keyPasses: 62,
      dribbles: 110,
      passAccuracy: 88.3,
      tackles: 74,
      interceptions: 45
    },
    radar: {
      pace: 96,
      shooting: 68,
      passing: 81,
      dribbling: 87,
      defending: 78,
      physical: 82,
      ego: 91
    },
    valueHistory: [
      { year: "2020", value: 80 },
      { year: "2021", value: 70 },
      { year: "2022", value: 70 },
      { year: "2023", value: 65 },
      { year: "2024", value: 50 }
    ],
    interestedClubs: [
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "MAXIMUM", offer: "€35M Now / Free in Jan", status: "Advanced Bids", probability: 90 },
      { clubId: "man-city", name: "Manchester City", league: "Premier League", interest: "MEDIUM", offer: "Contract Overtures", status: "Inquiry", probability: 20 }
    ]
  },
  {
    id: "rafael-leao",
    name: "Rafael Leão",
    image: "assets/players/leao.jpg",
    photo: "assets/players/leao.jpg",
    nationality: "Portugal",
    flag: "🇵🇹",
    age: 25,
    position: "Left Winger (LW)",
    currentClubId: "barcelona",
    currentClub: "AC Milan",
    targetClubId: "barcelona",
    targetClub: "FC Barcelona / PSG",
    shirtNumber: 10,
    preferredFoot: "Right",
    contractExpiry: "2028-06-30",
    marketValueRaw: 90,
    marketValue: "€90M",
    askingPrice: "€120M (Clause €175M)",
    reportedOffer: "€80M + Player Swap",
    valueDiff: "+€10M",
    transferType: "Permanent",
    transferStatus: "RUMOUR",
    probability: 45,
    confidence: 65,
    egoRating: 94,
    strikerIndex: 92,
    marketThreat: "VERY HIGH",
    momentum: 87,
    rating: 88,
    overview: "Gliding stride, uncatchable acceleration, and effortless swagger on the left flank.",
    stats: {
      appearances: 47,
      goals: 15,
      assists: 14,
      minutes: 3650,
      xg: 12.9,
      xa: 12.1,
      shots: 94,
      keyPasses: 76,
      dribbles: 148,
      passAccuracy: 81.9,
      tackles: 24,
      interceptions: 11
    },
    radar: {
      pace: 94,
      shooting: 84,
      passing: 82,
      dribbling: 93,
      defending: 30,
      physical: 80,
      ego: 94
    },
    valueHistory: [
      { year: "2021", value: 35 },
      { year: "2022", value: 70 },
      { year: "2023", value: 90 },
      { year: "2024", value: 90 }
    ],
    interestedClubs: [
      { clubId: "barcelona", name: "FC Barcelona", league: "La Liga", interest: "HIGH", offer: "€75M + Add-ons", status: "Agent Meeting Held", probability: 48 },
      { clubId: "psg", name: "Paris Saint-Germain", league: "Ligue 1", interest: "MEDIUM", offer: "€85M", status: "Monitoring", probability: 35 }
    ]
  },
  {
    id: "bukayo-saka",
    name: "Bukayo Saka",
    image: "assets/players/saka.jpg",
    photo: "assets/players/saka.jpg",
    nationality: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    age: 23,
    position: "Right Winger (RW)",
    currentClubId: "arsenal",
    currentClub: "Arsenal FC",
    targetClubId: "real-madrid",
    targetClub: "Real Madrid / Bayern Munich",
    shirtNumber: 7,
    preferredFoot: "Left",
    contractExpiry: "2027-06-30",
    marketValueRaw: 140,
    marketValue: "€140M",
    askingPrice: "Untouchable",
    reportedOffer: "€150M Rumour",
    valueDiff: "+€10M",
    transferType: "Contract Renewal",
    transferStatus: "CONFIRMED",
    probability: 5,
    confidence: 96,
    egoRating: 95,
    strikerIndex: 91,
    marketThreat: "SUPREME",
    momentum: 94,
    rating: 90,
    overview: "Iron-man consistency, elite decision making, relentless 1v1 separation, and clutch delivery.",
    stats: {
      appearances: 47,
      goals: 20,
      assists: 14,
      minutes: 3980,
      xg: 16.5,
      xa: 14.1,
      shots: 114,
      keyPasses: 102,
      dribbles: 118,
      passAccuracy: 84.8,
      tackles: 64,
      interceptions: 28
    },
    radar: {
      pace: 87,
      shooting: 86,
      passing: 89,
      dribbling: 91,
      defending: 59,
      physical: 78,
      ego: 95
    },
    valueHistory: [
      { year: "2020", value: 40 },
      { year: "2021", value: 65 },
      { year: "2022", value: 90 },
      { year: "2023", value: 120 },
      { year: "2024", value: 140 }
    ],
    interestedClubs: [
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "MEDIUM", offer: "Exploratory", status: "Untouchable", probability: 5 }
    ]
  },
  {
    id: "bruno-guimaraes",
    name: "Bruno Guimarães",
    image: "assets/players/bruno.jpg",
    photo: "assets/players/bruno.jpg",
    nationality: "Brazil",
    flag: "🇧🇷",
    age: 26,
    position: "Central Midfielder (CM / CDM)",
    currentClubId: "man-city",
    currentClub: "Newcastle United",
    targetClubId: "man-city",
    targetClub: "Manchester City",
    shirtNumber: 39,
    preferredFoot: "Right",
    contractExpiry: "2028-06-30",
    marketValueRaw: 85,
    marketValue: "€85M",
    askingPrice: "€100M",
    reportedOffer: "€85M + Bonuses",
    valueDiff: "+€15M",
    transferType: "Permanent",
    transferStatus: "NEGOTIATING",
    probability: 68,
    confidence: 80,
    egoRating: 92,
    strikerIndex: 83,
    marketThreat: "HIGH",
    momentum: 88,
    rating: 88,
    overview: "Tenacious midfield general with press-resistant elegance, line-breaking passes, and battle-hardened grit.",
    stats: {
      appearances: 48,
      goals: 7,
      assists: 10,
      minutes: 4200,
      xg: 5.6,
      xa: 8.8,
      shots: 54,
      keyPasses: 76,
      dribbles: 88,
      passAccuracy: 88.0,
      tackles: 118,
      interceptions: 52
    },
    radar: {
      pace: 76,
      shooting: 78,
      passing: 89,
      dribbling: 87,
      defending: 85,
      physical: 87,
      ego: 92
    },
    valueHistory: [
      { year: "2021", value: 30 },
      { year: "2022", value: 50 },
      { year: "2023", value: 75 },
      { year: "2024", value: 85 }
    ],
    interestedClubs: [
      { clubId: "man-city", name: "Manchester City", league: "Premier League", interest: "VERY HIGH", offer: "€85M + Bonuses", status: "Advanced Bids", probability: 70 },
      { clubId: "psg", name: "Paris Saint-Germain", league: "Ligue 1", interest: "HIGH", offer: "€80M Bid", status: "Under Review", probability: 55 }
    ]
  },
  {
    id: "joshua-kimmich",
    name: "Joshua Kimmich",
    image: "assets/players/kimmich.jpg",
    photo: "assets/players/kimmich.jpg",
    nationality: "Germany",
    flag: "🇩🇪",
    age: 29,
    position: "Central Midfielder / Right Back (CM / RB)",
    currentClubId: "bayern-munich",
    currentClub: "Bayern Munich",
    targetClubId: "barcelona",
    targetClub: "FC Barcelona / PSG",
    shirtNumber: 6,
    preferredFoot: "Right",
    contractExpiry: "2025-06-30",
    marketValueRaw: 50,
    marketValue: "€50M",
    askingPrice: "€50M / Free 2025",
    reportedOffer: "€40M",
    valueDiff: "-€15M (Expiring Contract)",
    transferType: "Free Transfer / Permanent",
    transferStatus: "NEGOTIATING",
    probability: 65,
    confidence: 78,
    egoRating: 93,
    strikerIndex: 80,
    marketThreat: "HIGH",
    momentum: 82,
    rating: 89,
    overview: "Supreme tactical brain with pinpoint diagonal deliveries, leadership grit, and dual-role versatility.",
    stats: {
      appearances: 43,
      goals: 4,
      assists: 12,
      minutes: 3690,
      xg: 3.2,
      xa: 11.8,
      shots: 42,
      keyPasses: 98,
      dribbles: 32,
      passAccuracy: 91.2,
      tackles: 82,
      interceptions: 49
    },
    radar: {
      pace: 70,
      shooting: 76,
      passing: 94,
      dribbling: 82,
      defending: 84,
      physical: 81,
      ego: 93
    },
    valueHistory: [
      { year: "2020", value: 85 },
      { year: "2021", value: 90 },
      { year: "2022", value: 80 },
      { year: "2023", value: 75 },
      { year: "2024", value: 50 }
    ],
    interestedClubs: [
      { clubId: "barcelona", name: "FC Barcelona", league: "La Liga", interest: "VERY HIGH", offer: "Free Pre-Contract 2025", status: "Direct Flick Contact", probability: 68 },
      { clubId: "psg", name: "Paris Saint-Germain", league: "Ligue 1", interest: "HIGH", offer: "€40M Bid Formula", status: "Monitoring", probability: 45 },
      { clubId: "man-city", name: "Manchester City", league: "Premier League", interest: "MEDIUM", offer: "Inquiry", status: "Guardiola Target", probability: 40 }
    ]
  }
];

export const LIVE_TRANSFERS = [
  {
    id: "tr-1",
    playerId: "julian-alvarez",
    playerName: "Julián Álvarez",
    image: "assets/players/alvarez.jpg",
    playerPhoto: "assets/players/alvarez.jpg",
    age: 24,
    position: "Forward",
    fromClub: "Manchester City",
    fromClubId: "man-city",
    fromBadge: "assets/clubs/man-city.png",
    toClub: "FC Barcelona",
    toClubId: "barcelona",
    toBadge: "assets/clubs/barcelona.png",
    marketValue: "€85M",
    reportedFee: "€90M",
    status: "NEGOTIATING",
    transferType: "Permanent",
    confidence: 78,
    timeAgo: "12 mins ago",
    egoThreat: "HIGH",
    headline: "Barcelona accelerate direct negotiations with agent for €90M package structure."
  },
  {
    id: "tr-2",
    playerId: "victor-osimhen",
    playerName: "Victor Osimhen",
    image: "assets/players/osimhen.jpg",
    playerPhoto: "assets/players/osimhen.jpg",
    age: 25,
    position: "Striker",
    fromClub: "Napoli",
    fromClubId: "chelsea",
    fromBadge: "assets/clubs/napoli.png",
    toClub: "Arsenal FC",
    toClubId: "arsenal",
    toBadge: "assets/clubs/arsenal.png",
    marketValue: "€100M",
    reportedFee: "€110M",
    status: "NEGOTIATING",
    transferType: "Permanent",
    confidence: 84,
    timeAgo: "25 mins ago",
    egoThreat: "CRITICAL",
    headline: "Arsenal submitted improved salary package; final clause discussion underway."
  },
  {
    id: "tr-3",
    playerId: "kylian-mbappe",
    playerName: "Kylian Mbappé",
    image: "assets/players/mbappe.jpg",
    playerPhoto: "assets/players/mbappe.jpg",
    age: 25,
    position: "Forward",
    fromClub: "Paris Saint-Germain",
    fromClubId: "psg",
    fromBadge: "assets/clubs/psg.png",
    toClub: "Real Madrid",
    toClubId: "real-madrid",
    toBadge: "assets/clubs/real-madrid.png",
    marketValue: "€180M",
    reportedFee: "Free (€150M Bonus)",
    status: "CONFIRMED",
    transferType: "Free Transfer",
    confidence: 100,
    timeAgo: "1 hour ago",
    egoThreat: "SUPREME",
    headline: "Official presentation completed at Bernabéu with 85,000 screaming fans."
  },
  {
    id: "tr-4",
    playerId: "alphonso-davies",
    playerName: "Alphonso Davies",
    image: "assets/players/davies.jpg",
    playerPhoto: "assets/players/davies.jpg",
    age: 23,
    position: "Left Back",
    fromClub: "Bayern Munich",
    fromClubId: "bayern-munich",
    fromBadge: "assets/clubs/bayern.png",
    toClub: "Real Madrid",
    toClubId: "real-madrid",
    toBadge: "assets/clubs/real-madrid.png",
    marketValue: "€50M",
    reportedFee: "€40M + €10M",
    status: "NEGOTIATING",
    transferType: "Permanent",
    confidence: 88,
    timeAgo: "2 hours ago",
    egoThreat: "HIGH",
    headline: "Personal terms 100% agreed on 5-year deal; clubs finalizing payment installments."
  },
  {
    id: "tr-5",
    playerId: "florian-wirtz",
    playerName: "Florian Wirtz",
    image: "assets/players/wirtz.jpg",
    playerPhoto: "assets/players/wirtz.jpg",
    age: 21,
    position: "Attacking Mid",
    fromClub: "Bayer Leverkusen",
    fromClubId: "bayern-munich",
    fromBadge: "assets/clubs/leverkusen.png",
    toClub: "Real Madrid",
    toClubId: "real-madrid",
    toBadge: "assets/clubs/real-madrid.png",
    marketValue: "€130M",
    reportedFee: "€150M",
    status: "RUMOUR",
    transferType: "Permanent",
    confidence: 72,
    timeAgo: "3 hours ago",
    egoThreat: "CRITICAL",
    headline: "Bidding war looms for summer 2025 as Real Madrid, Bayern & Man City line up record bids."
  },
  {
    id: "tr-6",
    playerId: "bruno-guimaraes",
    playerName: "Bruno Guimarães",
    image: "assets/players/bruno.jpg",
    playerPhoto: "assets/players/bruno.jpg",
    age: 26,
    position: "Central Mid",
    fromClub: "Newcastle United",
    fromClubId: "man-city",
    fromBadge: "assets/clubs/newcastle.png",
    toClub: "Manchester City",
    toClubId: "man-city",
    toBadge: "assets/clubs/man-city.png",
    marketValue: "€85M",
    reportedFee: "€100M",
    status: "NEGOTIATING",
    transferType: "Permanent",
    confidence: 68,
    timeAgo: "4 hours ago",
    egoThreat: "HIGH",
    headline: "Guardiola designates Bruno as top priority engine; Newcastle demand full valuation."
  },
  {
    id: "tr-7",
    playerId: "joshua-kimmich",
    playerName: "Joshua Kimmich",
    image: "assets/players/kimmich.jpg",
    playerPhoto: "assets/players/kimmich.jpg",
    age: 29,
    position: "Central Mid / RB",
    fromClub: "Bayern Munich",
    fromClubId: "bayern-munich",
    fromBadge: "assets/clubs/bayern.png",
    toClub: "FC Barcelona",
    toClubId: "barcelona",
    toBadge: "assets/clubs/barcelona.png",
    marketValue: "€50M",
    reportedFee: "Free (2025 Pre-contract)",
    status: "FREE TRANSFER",
    transferType: "Free Transfer",
    confidence: 65,
    timeAgo: "5 hours ago",
    egoThreat: "MEDIUM",
    headline: "Hansi Flick in direct weekly contact; contract expiration strategy being executed."
  },
  {
    id: "tr-8",
    playerId: "rafael-leao",
    playerName: "Rafael Leão",
    image: "assets/players/leao.jpg",
    playerPhoto: "assets/players/leao.jpg",
    age: 25,
    position: "Left Winger",
    fromClub: "AC Milan",
    fromClubId: "barcelona",
    fromBadge: "assets/clubs/milan.png",
    toClub: "FC Barcelona",
    toClubId: "barcelona",
    toBadge: "assets/clubs/barcelona.png",
    marketValue: "€90M",
    reportedFee: "€95M",
    status: "RUMOUR",
    transferType: "Permanent",
    confidence: 45,
    timeAgo: "6 hours ago",
    egoThreat: "HIGH",
    headline: "Jorge Mendes exploring feasibility; AC Milan refuse any discount below €100M."
  },
  {
    id: "tr-9",
    playerId: "alexander-isak",
    playerName: "Alexander Isak",
    image: "assets/players/isak.jpg",
    playerPhoto: "assets/players/isak.jpg",
    age: 24,
    position: "Striker",
    fromClub: "Newcastle United",
    fromClubId: "arsenal",
    fromBadge: "assets/clubs/newcastle.png",
    toClub: "Arsenal FC",
    toClubId: "arsenal",
    toBadge: "assets/clubs/arsenal.png",
    marketValue: "€75M",
    reportedFee: "€95M",
    status: "RUMOUR",
    transferType: "Permanent",
    confidence: 60,
    timeAgo: "7 hours ago",
    egoThreat: "HIGH",
    headline: "Arteta prioritizes dynamic striker profile; Newcastle prepare bumper new contract offer."
  },
  {
    id: "tr-10",
    playerId: "jamal-musiala",
    playerName: "Jamal Musiala",
    image: "assets/players/musiala.jpg",
    playerPhoto: "assets/players/musiala.jpg",
    age: 21,
    position: "Attacking Mid",
    fromClub: "Bayern Munich",
    fromClubId: "bayern-munich",
    fromBadge: "assets/clubs/bayern.png",
    toClub: "Manchester City",
    toClubId: "man-city",
    toBadge: "assets/clubs/man-city.png",
    marketValue: "€130M",
    reportedFee: "€130M",
    status: "NEGOTIATING",
    transferType: "Contract Battle",
    confidence: 54,
    timeAgo: "8 hours ago",
    egoThreat: "CRITICAL",
    headline: "Musiala delays contract extension signature amidst intense Man City interest."
  }
];

export const TRANSFER_NEWS = [
  {
    id: "news-1",
    title: "BREAKING: Julián Álvarez in Advanced Talks as Barcelona Push €90M Mega Deal",
    summary: "The Argentine World Cup champion is ready to take primary focal striker duties in Spain. Manchester City and Barcelona are in final formula discussions.",
    content: "Barcelona have submitted an escalated bid for Julián Álvarez consisting of €75M fixed plus €15M easily achievable performance add-ons. Hansi Flick has directly spoken with the striker, promising him the absolute #9 starting talisman role in the post-Lewandowski era. City hierarchy are open to finalizing the exit if their full valuation is matched.",
    player: "Julián Álvarez",
    playerId: "julian-alvarez",
    clubs: ["Manchester City", "FC Barcelona"],
    status: "NEGOTIATING",
    category: "NEGOTIATIONS",
    source: "BlueLock Tactical Wire",
    published: "18 mins ago",
    readTime: "3 min read",
    image: "assets/players/alvarez.jpg",
    egoImpact: "HIGH IMPACT (+18% Squad Dominance)"
  },
  {
    id: "news-2",
    title: "CONFIRMED: Kylian Mbappé Unveiled at Santiago Bernabéu in Galactic Era 2.0",
    summary: "Real Madrid complete the century's biggest free transfer. Number 9 shirt claimed and 85,000 supporters create historic atmosphere.",
    content: "Florentino Pérez welcomed Kylian Mbappé on stage at the Santiago Bernabéu. The French superstar signed a 5-year deal worth €15M net per year alongside a monumental €150M signing bonus amortized across his contract. Mbappé: 'My childhood dream has become my daily reality. We will conquer every title.'",
    player: "Kylian Mbappé",
    playerId: "kylian-mbappe",
    clubs: ["Real Madrid", "Paris Saint-Germain"],
    status: "CONFIRMED",
    category: "CONFIRMED",
    source: "Madrid Intelligence Hub",
    published: "1 hour ago",
    readTime: "4 min read",
    image: "assets/players/mbappe.jpg",
    egoImpact: "MAXIMUM (Ego Rating 99 Achieved)"
  },
  {
    id: "news-3",
    title: "TRANSFER BATTLE: Arsenal vs Chelsea in Final Showdown for Victor Osimhen",
    summary: "Napoli's explosive striker has two massive Premier League contract proposals on his desk. Break clause negotiations enter decisive 48 hours.",
    content: "Mikel Arteta has personally met Osimhen's representatives in London, outlining how his lightning box transitions and aerial mastery can deliver Arsenal the Premier League crown. Chelsea remain active with Todd Boehly ready to match the wage structure. Napoli president Aurelio De Laurentiis demands €100M+ guarantee.",
    player: "Victor Osimhen",
    playerId: "victor-osimhen",
    clubs: ["Arsenal FC", "Chelsea FC", "Napoli"],
    status: "NEGOTIATING",
    category: "NEGOTIATIONS",
    source: "London Scout Network",
    published: "2 hours ago",
    readTime: "3 min read",
    image: "assets/players/osimhen.jpg",
    egoImpact: "CRITICAL (Top Tier Striker Index 97)"
  },
  {
    id: "news-4",
    title: "RUMOUR: Florian Wirtz 2025 Master Plan - Real Madrid Prepare €150M Strategic Bid",
    summary: "Leverkusen's talisman playmaker is being tracked by every top 5 club, but the Spanish champions are leading the scouting queue.",
    content: "Following his unforgettable unbeaten Bundesliga season under Xabi Alonso, Florian Wirtz is evaluating his long-term career projection. Real Madrid scouts have delivered a unanimous 'Grade A+' evaluation, viewing Wirtz as the natural heir to Luka Modrić's creative midfield throne. Bayern Munich have vowed to counter with their own German record bid.",
    player: "Florian Wirtz",
    playerId: "florian-wirtz",
    clubs: ["Real Madrid", "Bayern Munich", "Bayer Leverkusen"],
    status: "RUMOUR",
    category: "RUMOURS",
    source: "European Scouting Bureau",
    published: "4 hours ago",
    readTime: "5 min read",
    image: "assets/players/wirtz.jpg",
    egoImpact: "HIGH THREAT (Vision 93 / IQ 95)"
  },
  {
    id: "news-5",
    title: "LOAN REPORT: Strategic Loan Deals Reshaping Mid-Tier Title Races Across Europe",
    summary: "Top clubs utilize high-value development loans with mandatory conditional buy clauses to balance Financial Fair Play books.",
    content: "With UEFA financial sustainability regulations tightening across all five major leagues, clubs are increasingly turning to structured loans featuring performance buy triggers. Look at recent masterstrokes like Vitor Roque, Conor Gallagher, and Raheem Sterling as clubs aggressively manage squad amortization.",
    player: "Multiple Stars",
    playerId: "julian-alvarez",
    clubs: ["Chelsea FC", "Arsenal FC", "FC Barcelona"],
    status: "LOAN",
    category: "LOANS",
    source: "Financial Fair Play Analytics",
    published: "6 hours ago",
    readTime: "4 min read",
    image: "assets/players/haaland.jpg",
    egoImpact: "TACTICAL FLEXIBILITY"
  },
  {
    id: "news-6",
    title: "FREE AGENTS 2025: Kimmich, Davies & Salah Headline Blockbuster Expiring Class",
    summary: "Over €400M in world-class market valuation enters the final 10 months of contracts, sparking furious January pre-contract maneuvers.",
    content: "The free agent battlefield is set to ignite this winter. With Joshua Kimmich refusing Bayern's reduced wage structure, Alphonso Davies eyeing Real Madrid, and Mohamed Salah weighing Middle Eastern vs European offers, clubs are executing intricate long-game scouting operations.",
    player: "Joshua Kimmich",
    playerId: "joshua-kimmich",
    clubs: ["Bayern Munich", "FC Barcelona", "Liverpool FC"],
    status: "FREE TRANSFER",
    category: "FREE TRANSFERS",
    source: "Contract Legal Radar",
    published: "8 hours ago",
    readTime: "3 min read",
    image: "assets/players/kimmich.jpg",
    egoImpact: "ZERO FEE / MAX SALARY"
  }
];

export const DASHBOARD_STATS = {
  activeRumours: 42,
  confirmedTransfers: 18,
  biggestTransfer: {
    player: "Kylian Mbappé",
    fee: "€180M Val.",
    club: "Real Madrid"
  },
  mostValuablePlayer: {
    name: "Kylian Mbappé / Erling Haaland / Jude Bellingham",
    value: "€180M"
  },
  mostActiveClub: {
    name: "Real Madrid",
    deals: 6,
    spend: "€197.5M"
  },
  totalMarketSpend: "€2.84B",
  avgEgoRating: 94.2
};
