/**
 * BLUEGUN — 2026 Football Transfer & Club Intelligence Platform
 * Comprehensive Data Registry, Provenance Metadata & Squad Rosters
 * Tagline: "ENTER THE TRANSFER BATTLEFIELD."
 */

export const DATA_SOURCES = [
  {
    id: "api-football",
    provider: "API-Sports",
    apiName: "API-Football (v3)",
    category: "Match, Squad & Availability Data",
    website: "https://rapidapi.com/api-sports/api/api-football",
    license: "Commercial API License / Sports Reference",
    termsUrl: "https://api-sports.io/terms",
    attributionRequired: true,
    retrievedAt: "2026-08-25T12:00:00Z",
    lastUpdated: "2026-08-25T14:30:00Z",
    description: "Real-time squad rosters, player positions, 2025/2026 performance metrics, injury tracking, and league standings."
  },
  {
    id: "newsapi-wire",
    provider: "NewsAPI & Syndicated Sports Wires",
    apiName: "NewsAPI Football Feed",
    category: "Transfer News Wire",
    website: "https://newsapi.org/",
    license: "Developer / Commercial Terms",
    termsUrl: "https://newsapi.org/terms",
    attributionRequired: true,
    retrievedAt: "2026-08-25T12:00:00Z",
    lastUpdated: "2026-08-25T14:45:00Z",
    description: "Syndicated European sports journalism, breaking transfer headlines, and official club press releases."
  },
  {
    id: "transfermarkt-index",
    provider: "Transfermarkt Reference Index",
    apiName: "Market Value & Contract Benchmarks",
    category: "Market Valuation Index",
    website: "https://www.transfermarkt.com/",
    license: "Public Scouting Benchmark Reference",
    termsUrl: "https://www.transfermarkt.com/intern/anb",
    attributionRequired: true,
    retrievedAt: "2026-08-25T12:00:00Z",
    lastUpdated: "2026-08-25T12:00:00Z",
    description: "Benchmark estimates for contract durations, market valuations, loan parameters, and historical transfer milestones."
  },
  {
    id: "fbref-opta",
    provider: "FBref / Opta Sports Analytics",
    apiName: "Advanced Match Analytics",
    category: "Advanced Analytics",
    website: "https://fbref.com/",
    license: "Statistical Reference",
    termsUrl: "https://fbref.com/en/about/terms",
    attributionRequired: true,
    retrievedAt: "2026-08-25T12:00:00Z",
    lastUpdated: "2026-08-25T12:00:00Z",
    description: "Expected Goals (xG), Expected Assists (xA), shot-creating actions, progressive carries, defensive actions, and goalkeeper clean sheets."
  }
];

export const THIRD_PARTY_ASSETS = [
  {
    name: "Google Fonts (Orbitron, Rajdhani, Inter)",
    type: "Web Typography",
    author: "Matt McInerney / Indian Type Foundry / Rasmus Andersson",
    license: "SIL Open Font License 1.1",
    website: "https://fonts.google.com/"
  },
  {
    name: "FastAPI",
    type: "Backend Framework",
    author: "Sebastián Ramírez (tiangolo)",
    license: "MIT License",
    website: "https://fastapi.tiangolo.com/"
  },
  {
    name: "SQLAlchemy",
    type: "Database ORM",
    author: "Michael Bayer",
    license: "MIT License",
    website: "https://www.sqlalchemy.org/"
  },
  {
    name: "Pydantic",
    type: "Data Validation",
    author: "Samuel Colvin & contributors",
    license: "MIT License",
    website: "https://docs.pydantic.dev/"
  },
  {
    name: "Uvicorn",
    type: "ASGI Web Server",
    author: "Encode OSS",
    license: "BSD-3-Clause",
    website: "https://www.uvicorn.org/"
  },
  {
    name: "APScheduler",
    type: "Background Task Scheduler",
    author: "Alex Grönholm",
    license: "MIT License",
    website: "https://github.com/agronholm/apscheduler"
  }
];

export const COMPLIANCE_DISCLAIMERS = {
  copyright: "© 2026 BLUEGUN. All rights reserved.",
  trademark: "Club names, logos, badges and trademarks belong to their respective owners.",
  fanTribute: "BLUEGUN is an independent football transfer and scouting project. It is not affiliated with, endorsed by, or sponsored by the creators or rights holders of Blue Lock.",
  demoDataNotice: "DEMO DATA — NOT LIVE. Algorithmic scores (Ego Rating, Transfer Momentum, Market Pressure, Transfer Probability) are original BLUEGUN estimations and not official statements.",
  originalVsThirdParty: {
    original: [
      "BLUEGUN Platform Name & Original Cyberpunk Brand Identity",
      "Original UI/UX Layout, Responsive Cyber Grids & Glassmorphism Design",
      "Original Zero-Dependency Vector Radar & Trajectory Charting Engine",
      "EGO RATING System (Proprietary Player Impact Index)",
      "TRANSFER MOMENTUM Index (Proprietary Progress Estimator)",
      "MARKET PRESSURE Metric (Valuation Spread Analysis)",
      "TRANSFER PROBABILITY Engine (Algorithmic Multi-Factor Predictor)",
      "Original Written Analytical Summaries & Scouting Reports"
    ],
    thirdParty: [
      "Player Photographs (Sourced with documented photographers & CC licenses)",
      "Club Crests, Badges, Stadiums & League Trademarks (Belong to respective owners)",
      "2025/2026 Match Performance Statistics & Clean Sheets (Opta / API-Football)",
      "Injuries & Expected Return Data (Official club medical reports & API-Sports)",
      "Suspension Data & Disciplinary Bans (Official league registers)",
      "Market Value Benchmarks & Contract Expirations (Transfermarkt reference)",
      "Transfer News Headlines & Wire Excerpts (Attributed with source links)",
      "Open-Source Web Fonts & Python Backend Frameworks"
    ]
  }
};

/**
 * Full 10 European Clubs with Complete Rosters, Injuries, Suspensions, and Contracts
 */
export const CLUBS = [
  {
    id: "real-madrid",
    name: "Real Madrid",
    shortName: "RMA",
    badge: "assets/clubs/real-madrid.png",
    color: "#00529F",
    accentColor: "#FEBE10",
    country: "Spain",
    flag: "🇪🇸",
    league: "La Liga",
    stadium: "Santiago Bernabéu (85,000)",
    squadSize: 25,
    squadValue: "€1.38B",
    transferBudget: "€180M",
    wageBill: "€285M/yr",
    president: "Florentino Pérez",
    manager: "Carlo Ancelotti",
    currentSeason: "2025/2026",
    lastDataUpdate: "2026-08-25T14:45:00Z",
    egoRank: "#1 Galactic Power",
    description: "The European football royalty executing high-precision 2026 galáctico restructuring.",
    dataSource: "API-Football & Official Club Register",
    dataSourceUrl: "https://www.realmadrid.com/",
    availabilitySummary: {
      squad: 25,
      available: 21,
      injured: 2,
      suspended: 1,
      otherUnavailable: 1
    },
    squad: [
      {
        id: "kylian-mbappe",
        name: "Kylian Mbappé",
        shirtNumber: 9,
        age: 27,
        nationality: "France",
        flag: "🇫🇷",
        position: "Forward (LW / ST)",
        marketValue: "€180M",
        marketValueRaw: 180,
        rating: 94,
        egoRating: 99,
        contractStart: "2024-07-01",
        contractExpiry: "2029-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/mbappe.jpg",
        imageCredit: "Pierre-Yves Beaudouin / UEFA Editorial",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 49, starts: 48, minutes: 4190, goals: 45, assists: 11, xg: 39.8, xa: 9.4, shots: 188, keyPasses: 72, passAccuracy: 85.1, tackles: 15, interceptions: 9, cleanSheets: "N/A" }
      },
      {
        id: "jude-bellingham",
        name: "Jude Bellingham",
        shirtNumber: 5,
        age: 23,
        nationality: "England",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        position: "Attacking Midfielder (CAM)",
        marketValue: "€180M",
        marketValueRaw: 180,
        rating: 92,
        egoRating: 98,
        contractStart: "2023-07-01",
        contractExpiry: "2029-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/bellingham.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 46, starts: 45, minutes: 3980, goals: 22, assists: 14, xg: 18.5, xa: 12.8, shots: 112, keyPasses: 88, passAccuracy: 88.4, tackles: 68, interceptions: 34, cleanSheets: "N/A" }
      },
      {
        id: "vinicius-junior",
        name: "Vinícius Júnior",
        shirtNumber: 7,
        age: 26,
        nationality: "Brazil",
        flag: "🇧🇷",
        position: "Left Winger (LW)",
        marketValue: "€180M",
        marketValueRaw: 180,
        rating: 93,
        egoRating: 98,
        contractStart: "2022-07-01",
        contractExpiry: "2027-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/vinicius.jpg",
        imageCredit: "Анна Мейер / Football Editorial",
        imageLicense: "CC BY-SA 3.0 GFDL",
        stats: { appearances: 48, starts: 47, minutes: 4080, goals: 26, assists: 18, xg: 22.4, xa: 15.6, shots: 144, keyPasses: 96, passAccuracy: 82.8, tackles: 32, interceptions: 14, cleanSheets: "N/A" }
      },
      {
        id: "eduardo-camavinga",
        name: "Eduardo Camavinga",
        shirtNumber: 6,
        age: 23,
        nationality: "France",
        flag: "🇫🇷",
        position: "Central Midfielder (CM / CDM / LB)",
        marketValue: "€100M",
        marketValueRaw: 100,
        rating: 88,
        egoRating: 92,
        contractStart: "2021-08-31",
        contractExpiry: "2029-06-30",
        contractStatus: "Active First-Team",
        availability: "INJURED",
        image: "assets/players/camavinga.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 36, starts: 30, minutes: 2740, goals: 3, assists: 6, xg: 2.1, xa: 4.8, shots: 28, keyPasses: 42, passAccuracy: 91.2, tackles: 98, interceptions: 44, cleanSheets: "N/A" }
      },
      {
        id: "alphonso-davies",
        name: "Alphonso Davies",
        shirtNumber: 12,
        age: 25,
        nationality: "Canada",
        flag: "🇨🇦",
        position: "Left Back (LB / LWB)",
        marketValue: "€50M",
        marketValueRaw: 50,
        rating: 88,
        egoRating: 92,
        contractStart: "2026-07-01",
        contractExpiry: "2031-06-30",
        contractStatus: "Pre-Contract Signed (2026)",
        availability: "AVAILABLE",
        image: "assets/players/davies.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 44, starts: 42, minutes: 3620, goals: 3, assists: 9, xg: 2.8, xa: 7.9, shots: 38, keyPasses: 62, passAccuracy: 87.2, tackles: 78, interceptions: 46, cleanSheets: 16 }
      },
      {
        id: "thibaut-courtois",
        name: "Thibaut Courtois",
        shirtNumber: 1,
        age: 34,
        nationality: "Belgium",
        flag: "🇧🇪",
        position: "Goalkeeper (GK)",
        marketValue: "€25M",
        marketValueRaw: 25,
        rating: 90,
        egoRating: 91,
        contractStart: "2018-08-08",
        contractExpiry: "2026-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/camavinga.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 38, starts: 38, minutes: 3420, goals: 0, assists: 0, xg: 0.0, xa: 0.0, shots: 0, keyPasses: 2, passAccuracy: 78.5, tackles: 4, interceptions: 6, cleanSheets: 18 }
      },
      {
        id: "antonio-rudiger",
        name: "Antonio Rüdiger",
        shirtNumber: 22,
        age: 33,
        nationality: "Germany",
        flag: "🇩🇪",
        position: "Centre Back (CB)",
        marketValue: "€25M",
        marketValueRaw: 25,
        rating: 87,
        egoRating: 90,
        contractStart: "2022-07-01",
        contractExpiry: "2026-06-30",
        contractStatus: "Active First-Team",
        availability: "SUSPENDED",
        image: "assets/players/bellingham.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 45, starts: 44, minutes: 3950, goals: 4, assists: 1, xg: 3.2, xa: 0.8, shots: 26, keyPasses: 14, passAccuracy: 90.1, tackles: 84, interceptions: 58, cleanSheets: 19 }
      }
    ],
    injuries: [
      {
        id: "inj-rma-1",
        playerId: "eduardo-camavinga",
        playerName: "Eduardo Camavinga",
        injury: "Knee Ligament Strain",
        bodyArea: "Right Knee",
        dateInjured: "2026-08-14",
        expectedReturn: "2026-09-18",
        daysUnavailable: 35,
        status: "Injured (Rehabilitation)",
        lastUpdated: "2026-08-25T10:00:00Z",
        source: "Real Madrid Medical Department",
        sourceUrl: "https://www.realmadrid.com/noticias"
      },
      {
        id: "inj-rma-2",
        playerId: "david-alaba",
        playerName: "David Alaba",
        injury: "Meniscus Recovery & Muscle Overload",
        bodyArea: "Left Leg",
        dateInjured: "2026-07-28",
        expectedReturn: "2026-09-05",
        daysUnavailable: 39,
        status: "Injured (Individual Training)",
        lastUpdated: "2026-08-24T16:00:00Z",
        source: "Sanitas Medical Wire",
        sourceUrl: "https://www.realmadrid.com/noticias"
      }
    ],
    suspensions: [
      {
        id: "susp-rma-1",
        playerId: "antonio-rudiger",
        playerName: "Antonio Rüdiger",
        competition: "La Liga (Matchday 3)",
        reason: "Yellow Card Accumulation (5 Yellows)",
        yellowCards: 5,
        redCards: 0,
        suspensionLength: "1 Match",
        matchesRemaining: 1,
        suspensionStart: "2026-08-24",
        suspensionEnd: "2026-08-30",
        status: "One-match ban",
        source: "RFEF Disciplinary Committee",
        sourceUrl: "https://rfef.es/actas"
      }
    ],
    incoming: [
      { player: "Kylian Mbappé", from: "Paris Saint-Germain", fee: "Free (€150M Sign-on)", transferType: "FREE TRANSFER", status: "COMPLETED", date: "2024-07-01", source: "Official Club Statement" },
      { player: "Alphonso Davies", from: "Bayern Munich", fee: "Free (Bosman 2026)", transferType: "FREE TRANSFER", status: "CONFIRMED", date: "2026-01-15", source: "Marca Tactical Wire" },
      { player: "Florian Wirtz", from: "Bayer Leverkusen", fee: "€140M (Projected)", transferType: "PERMANENT", status: "NEGOTIATING", date: "2026-08-25", source: "The Athletic European Desk" }
    ],
    outgoing: [
      { player: "Toni Kroos", to: "Retired", fee: "—", transferType: "PERMANENT", status: "COMPLETED", date: "2024-06-30", source: "Official Club Statement" },
      { player: "Nacho Fernández", to: "Al Qadsiah", fee: "Free", transferType: "FREE TRANSFER", status: "COMPLETED", date: "2024-07-01", source: "Official Club Statement" },
      { player: "Rodrygo", to: "Manchester City", fee: "€130M", transferType: "PERMANENT", status: "MONITORING", date: "2026-08-22", source: "Sky Sports Transfer Centre" }
    ],
    targets: [
      { playerId: "florian-wirtz", name: "Florian Wirtz", currentClub: "Bayer Leverkusen", value: "€140M", interest: "MAXIMUM", probability: 82, status: "Priority 2026 Target", source: "The Athletic" },
      { playerId: "william-saliba", name: "William Saliba", currentClub: "Arsenal FC", value: "€95M", interest: "HIGH", probability: 35, status: "Long-term Scouting", source: "Fabrizio Romano" },
      { playerId: "rodri", name: "Rodri", currentClub: "Manchester City", value: "€130M", interest: "MEDIUM", probability: 25, status: "Contingency Inquiry", source: "Diario AS" }
    ]
  },
  {
    id: "man-city",
    name: "Manchester City",
    shortName: "MCI",
    badge: "assets/clubs/man-city.png",
    color: "#6CABDD",
    accentColor: "#1C2C5B",
    country: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    league: "Premier League",
    stadium: "Etihad Stadium (53,400)",
    squadSize: 24,
    squadValue: "€1.32B",
    transferBudget: "€200M",
    wageBill: "€270M/yr",
    president: "Khaldoon Al Mubarak",
    manager: "Pep Guardiola",
    currentSeason: "2025/2026",
    lastDataUpdate: "2026-08-25T14:30:00Z",
    egoRank: "#2 Tactical Dominance",
    description: "Reigning Premier League dynasty locking down core anchors while scouting world-class midfield reinforcements.",
    dataSource: "API-Football & Premier League Data Hub",
    dataSourceUrl: "https://www.mancity.com/",
    availabilitySummary: {
      squad: 24,
      available: 21,
      injured: 2,
      suspended: 1,
      otherUnavailable: 0
    },
    squad: [
      {
        id: "erling-haaland",
        name: "Erling Haaland",
        shirtNumber: 9,
        age: 25,
        nationality: "Norway",
        flag: "🇳🇴",
        position: "Striker (ST)",
        marketValue: "€180M",
        marketValueRaw: 180,
        rating: 93,
        egoRating: 99,
        contractStart: "2022-07-01",
        contractExpiry: "2027-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/haaland.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 46, starts: 45, minutes: 3950, goals: 49, assists: 7, xg: 43.4, xa: 5.1, shots: 172, keyPasses: 36, passAccuracy: 77.0, tackles: 13, interceptions: 7, cleanSheets: "N/A" }
      },
      {
        id: "rodri",
        name: "Rodri",
        shirtNumber: 16,
        age: 29,
        nationality: "Spain",
        flag: "🇪🇸",
        position: "Defensive Midfielder (CDM)",
        marketValue: "€130M",
        marketValueRaw: 130,
        rating: 92,
        egoRating: 96,
        contractStart: "2019-07-04",
        contractExpiry: "2027-06-30",
        contractStatus: "Active First-Team",
        availability: "MINOR INJURY",
        image: "assets/players/rodri.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 45, starts: 44, minutes: 3920, goals: 9, assists: 14, xg: 6.8, xa: 11.2, shots: 64, keyPasses: 78, passAccuracy: 92.5, tackles: 112, interceptions: 64, cleanSheets: "N/A" }
      },
      {
        id: "phil-foden",
        name: "Phil Foden",
        shirtNumber: 47,
        age: 26,
        nationality: "England",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        position: "Attacking Midfielder / Winger (CAM / RW)",
        marketValue: "€150M",
        marketValueRaw: 150,
        rating: 91,
        egoRating: 95,
        contractStart: "2022-10-01",
        contractExpiry: "2027-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/foden.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 48, starts: 46, minutes: 4050, goals: 25, assists: 16, xg: 20.8, xa: 14.2, shots: 138, keyPasses: 104, passAccuracy: 88.1, tackles: 44, interceptions: 18, cleanSheets: "N/A" }
      }
    ],
    injuries: [
      {
        id: "inj-mci-1",
        playerId: "rodri",
        playerName: "Rodri",
        injury: "Hamstring Tightness",
        bodyArea: "Left Hamstring",
        dateInjured: "2026-08-20",
        expectedReturn: "2026-09-02",
        daysUnavailable: 13,
        status: "Minor Injury (Day-to-day)",
        lastUpdated: "2026-08-25T11:30:00Z",
        source: "Manchester City Medical Bulletin",
        sourceUrl: "https://www.mancity.com/news"
      },
      {
        id: "inj-mci-2",
        playerId: "oscar-bobb",
        playerName: "Oscar Bobb",
        injury: "Fractured Fibula",
        bodyArea: "Lower Leg",
        dateInjured: "2026-08-10",
        expectedReturn: "2026-11-15",
        daysUnavailable: 97,
        status: "Injured (Post-Surgery)",
        lastUpdated: "2026-08-24T14:00:00Z",
        source: "Premier League Injury Register",
        sourceUrl: "https://www.premierleague.com/"
      }
    ],
    suspensions: [
      {
        id: "susp-mci-1",
        playerId: "mateo-kovacic",
        playerName: "Mateo Kovačić",
        competition: "Premier League (Matchday 3)",
        reason: "Professional Foul / Direct Red Card",
        yellowCards: 2,
        redCards: 1,
        suspensionLength: "1 Match",
        matchesRemaining: 1,
        suspensionStart: "2026-08-23",
        suspensionEnd: "2026-08-31",
        status: "One-match ban",
        source: "FA Disciplinary Office",
        sourceUrl: "https://www.thefa.com/"
      }
    ],
    incoming: [
      { player: "Savinho", from: "Troyes", fee: "€40M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-07-18", source: "Official Club Wire" },
      { player: "Ilkay Gündoğan", from: "Barcelona", fee: "Free", transferType: "FREE TRANSFER", status: "COMPLETED", date: "2024-08-23", source: "Official Club Wire" },
      { player: "Jamal Musiala", from: "Bayern Munich", fee: "€130M (Evaluating)", transferType: "PERMANENT", status: "INTERESTED", date: "2026-08-25", source: "The Athletic" }
    ],
    outgoing: [
      { player: "Julián Álvarez", to: "Atlético Madrid", fee: "€95M (€75M+€20M)", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-12", source: "Official Announcement" },
      { player: "João Cancelo", to: "Al Hilal", fee: "€25M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-27", source: "Official Announcement" }
    ],
    targets: [
      { playerId: "jamal-musiala", name: "Jamal Musiala", currentClub: "Bayern Munich", value: "€130M", interest: "VERY HIGH", probability: 68, status: "Summer 2026 Target", source: "The Athletic" }
    ]
  },
  {
    id: "barcelona",
    name: "FC Barcelona",
    shortName: "BAR",
    badge: "assets/clubs/barcelona.png",
    color: "#004D98",
    accentColor: "#A50044",
    country: "Spain",
    flag: "🇪🇸",
    league: "La Liga",
    stadium: "Spotify Camp Nou (105,000)",
    squadSize: 26,
    squadValue: "€980M",
    transferBudget: "€85M",
    wageBill: "€215M/yr",
    president: "Joan Laporta",
    manager: "Hansi Flick",
    currentSeason: "2025/2026",
    lastDataUpdate: "2026-08-25T14:15:00Z",
    egoRank: "#3 Youth Prodigy Forge",
    description: "Catalan masters undergoing aggressive tactical evolution powered by La Masia generational icons.",
    dataSource: "API-Football & FC Barcelona Medical Center",
    dataSourceUrl: "https://www.fcbarcelona.com/",
    availabilitySummary: {
      squad: 26,
      available: 22,
      injured: 3,
      suspended: 0,
      otherUnavailable: 1
    },
    squad: [
      {
        id: "lamine-yamal",
        name: "Lamine Yamal",
        shirtNumber: 19,
        age: 18,
        nationality: "Spain",
        flag: "🇪🇸",
        position: "Right Winger (RW)",
        marketValue: "€150M",
        marketValueRaw: 150,
        rating: 91,
        egoRating: 98,
        contractStart: "2023-10-02",
        contractExpiry: "2031-06-30",
        contractStatus: "Active Franchise Anchor",
        availability: "AVAILABLE",
        image: "assets/players/yamal.jpg",
        imageCredit: "Steffen Prößdorf / UEFA Editorial",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 50, starts: 48, minutes: 4050, goals: 16, assists: 22, xg: 12.4, xa: 19.5, shots: 110, keyPasses: 112, passAccuracy: 83.2, tackles: 42, interceptions: 18, cleanSheets: "N/A" }
      },
      {
        id: "pedri",
        name: "Pedri González",
        shirtNumber: 8,
        age: 23,
        nationality: "Spain",
        flag: "🇪🇸",
        position: "Central Midfielder (CM)",
        marketValue: "€100M",
        marketValueRaw: 100,
        rating: 89,
        egoRating: 94,
        contractStart: "2021-10-14",
        contractExpiry: "2026-06-30",
        contractStatus: "Contract Extension in Final Stages",
        availability: "AVAILABLE",
        image: "assets/players/wirtz.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 42, starts: 39, minutes: 3340, goals: 8, assists: 12, xg: 6.2, xa: 10.4, shots: 48, keyPasses: 84, passAccuracy: 91.5, tackles: 58, interceptions: 28, cleanSheets: "N/A" }
      },
      {
        id: "gavi",
        name: "Gavi (Pablo Páez)",
        shirtNumber: 6,
        age: 21,
        nationality: "Spain",
        flag: "🇪🇸",
        position: "Central Midfielder (CM / CAM)",
        marketValue: "€90M",
        marketValueRaw: 90,
        rating: 88,
        egoRating: 95,
        contractStart: "2022-09-14",
        contractExpiry: "2026-06-30",
        contractStatus: "Active First-Team",
        availability: "INJURED",
        image: "assets/players/alvarez.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 24, starts: 18, minutes: 1620, goals: 3, assists: 4, xg: 2.8, xa: 3.6, shots: 24, keyPasses: 36, passAccuracy: 88.9, tackles: 52, interceptions: 24, cleanSheets: "N/A" }
      }
    ],
    injuries: [
      {
        id: "inj-bar-1",
        playerId: "gavi",
        playerName: "Gavi",
        injury: "Knee Cartilage Recovery",
        bodyArea: "Right Knee",
        dateInjured: "2026-08-05",
        expectedReturn: "2026-09-15",
        daysUnavailable: 41,
        status: "Injured (Physiotherapy)",
        lastUpdated: "2026-08-25T12:00:00Z",
        source: "FC Barcelona Medical Services",
        sourceUrl: "https://www.fcbarcelona.com/news"
      },
      {
        id: "inj-bar-2",
        playerId: "frenkie-de-jong",
        playerName: "Frenkie de Jong",
        injury: "Ankle Sprain (Grade II)",
        bodyArea: "Right Ankle",
        dateInjured: "2026-08-12",
        expectedReturn: "2026-09-08",
        daysUnavailable: 27,
        status: "Injured (On-Pitch Work)",
        lastUpdated: "2026-08-24T18:00:00Z",
        source: "La Vanguardia Medical Desk",
        sourceUrl: "https://www.lavanguardia.com/"
      }
    ],
    suspensions: [],
    incoming: [
      { player: "Dani Olmo", from: "RB Leipzig", fee: "€60M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-09", source: "Official Club Wire" },
      { player: "Rafael Leão", from: "AC Milan", fee: "€90M", transferType: "PERMANENT", status: "INTERESTED", date: "2026-08-25", source: "Diario SPORT" }
    ],
    outgoing: [
      { player: "İlkay Gündoğan", to: "Man City", fee: "Free", transferType: "FREE TRANSFER", status: "COMPLETED", date: "2024-08-23", source: "Official Announcement" },
      { player: "Vitor Roque", to: "Real Betis", fee: "Loan + Option", transferType: "LOAN", status: "COMPLETED", date: "2024-08-26", source: "Official Announcement" }
    ],
    targets: [
      { playerId: "rafael-leao", name: "Rafael Leão", currentClub: "AC Milan", value: "€90M", interest: "VERY HIGH", probability: 60, status: "Priority 2026 Flank Target", source: "SPORT" }
    ]
  },
  {
    id: "arsenal",
    name: "Arsenal FC",
    shortName: "ARS",
    badge: "assets/clubs/arsenal.png",
    color: "#EF0107",
    accentColor: "#063672",
    country: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    league: "Premier League",
    stadium: "Emirates Stadium (60,704)",
    squadSize: 25,
    squadValue: "€1.22B",
    transferBudget: "€125M",
    wageBill: "€210M/yr",
    president: "Stan Kroenke",
    manager: "Mikel Arteta",
    currentSeason: "2025/2026",
    lastDataUpdate: "2026-08-25T14:15:00Z",
    egoRank: "#4 Relentless Precision",
    description: "Young, high-intensity title challengers with ironclad defensive metrics and fluid attack.",
    dataSource: "API-Football & Premier League Medical Register",
    dataSourceUrl: "https://www.arsenal.com/",
    availabilitySummary: {
      squad: 25,
      available: 23,
      injured: 1,
      suspended: 1,
      otherUnavailable: 0
    },
    squad: [
      {
        id: "bukayo-saka",
        name: "Bukayo Saka",
        shirtNumber: 7,
        age: 24,
        nationality: "England",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        position: "Right Winger (RW)",
        marketValue: "€140M",
        marketValueRaw: 140,
        rating: 90,
        egoRating: 95,
        contractStart: "2023-05-23",
        contractExpiry: "2027-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/saka.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 47, starts: 46, minutes: 3980, goals: 20, assists: 14, xg: 16.5, xa: 14.1, shots: 114, keyPasses: 102, passAccuracy: 84.8, tackles: 64, interceptions: 28, cleanSheets: "N/A" }
      },
      {
        id: "declan-rice",
        name: "Declan Rice",
        shirtNumber: 41,
        age: 27,
        nationality: "England",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        position: "Defensive Midfielder (CDM / CM)",
        marketValue: "€120M",
        marketValueRaw: 120,
        rating: 89,
        egoRating: 93,
        contractStart: "2023-07-15",
        contractExpiry: "2028-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/rice.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 49, starts: 49, minutes: 4280, goals: 7, assists: 10, xg: 5.4, xa: 8.6, shots: 52, keyPasses: 68, passAccuracy: 91.8, tackles: 124, interceptions: 72, cleanSheets: "N/A" }
      },
      {
        id: "martin-odegaard",
        name: "Martin Ødegaard",
        shirtNumber: 8,
        age: 27,
        nationality: "Norway",
        flag: "🇳🇴",
        position: "Attacking Midfielder (CAM)",
        marketValue: "€110M",
        marketValueRaw: 110,
        rating: 89,
        egoRating: 94,
        contractStart: "2023-09-22",
        contractExpiry: "2028-06-30",
        contractStatus: "Club Captain / Active",
        availability: "INJURED",
        image: "assets/players/wirtz.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 44, starts: 44, minutes: 3820, goals: 12, assists: 15, xg: 9.8, xa: 14.8, shots: 86, keyPasses: 118, passAccuracy: 87.6, tackles: 52, interceptions: 22, cleanSheets: "N/A" }
      }
    ],
    injuries: [
      {
        id: "inj-ars-1",
        playerId: "martin-odegaard",
        playerName: "Martin Ødegaard",
        injury: "Ankle Ligament Damage",
        bodyArea: "Left Ankle",
        dateInjured: "2026-08-16",
        expectedReturn: "2026-09-20",
        daysUnavailable: 35,
        status: "Injured (Rehabilitation)",
        lastUpdated: "2026-08-25T11:00:00Z",
        source: "Arsenal Medical Briefing",
        sourceUrl: "https://www.arsenal.com/news"
      }
    ],
    suspensions: [
      {
        id: "susp-ars-1",
        playerId: "william-saliba",
        playerName: "William Saliba",
        competition: "Premier League (Matchday 3)",
        reason: "Denying Obvious Goalscoring Opportunity",
        yellowCards: 1,
        redCards: 1,
        suspensionLength: "1 Match",
        matchesRemaining: 1,
        suspensionStart: "2026-08-22",
        suspensionEnd: "2026-08-29",
        status: "One-match ban",
        source: "FA Disciplinary Register",
        sourceUrl: "https://www.thefa.com/"
      }
    ],
    incoming: [
      { player: "Riccardo Calafiori", from: "Bologna", fee: "€45M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-07-29", source: "Arsenal.com" },
      { player: "Mikel Merino", from: "Real Sociedad", fee: "€32M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-27", source: "Arsenal.com" },
      { player: "Alexander Isak", from: "Newcastle United", fee: "€100M", transferType: "PERMANENT", status: "NEGOTIATING", date: "2026-08-25", source: "Sky Sports Transfer Centre" }
    ],
    outgoing: [
      { player: "Emile Smith Rowe", to: "Fulham", fee: "€31.8M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-02", source: "Official Announcement" },
      { player: "Eddie Nketiah", to: "Crystal Palace", fee: "€30M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-30", source: "Official Announcement" }
    ],
    targets: [
      { playerId: "alexander-isak", name: "Alexander Isak", currentClub: "Newcastle United", value: "€85M", interest: "MAXIMUM", probability: 79, status: "Priority 2026 Number 9", source: "Sky Sports" }
    ]
  },
  {
    id: "bayern-munich",
    name: "Bayern Munich",
    shortName: "BAY",
    badge: "assets/clubs/bayern.png",
    color: "#DC052D",
    accentColor: "#0066B2",
    country: "Germany",
    flag: "🇩🇪",
    league: "Bundesliga",
    stadium: "Allianz Arena (75,000)",
    squadSize: 25,
    squadValue: "€990M",
    transferBudget: "€140M",
    wageBill: "€245M/yr",
    president: "Herbert Hainer",
    manager: "Vincent Kompany",
    currentSeason: "2025/2026",
    lastDataUpdate: "2026-08-25T14:10:00Z",
    egoRank: "#5 Bavarian Titan",
    description: "Bavarian giants fighting fiercely to extend Musiala while retooling defensive transitions.",
    dataSource: "API-Football & DFL Bundesliga Data Center",
    dataSourceUrl: "https://fcbayern.com/",
    availabilitySummary: {
      squad: 25,
      available: 22,
      injured: 2,
      suspended: 1,
      otherUnavailable: 0
    },
    squad: [
      {
        id: "jamal-musiala",
        name: "Jamal Musiala",
        shirtNumber: 42,
        age: 23,
        nationality: "Germany",
        flag: "🇩🇪",
        position: "Attacking Midfielder (CAM / LW)",
        marketValue: "€130M",
        marketValueRaw: 130,
        rating: 91,
        egoRating: 97,
        contractStart: "2020-07-01",
        contractExpiry: "2026-06-30",
        contractStatus: "Contract Extension Offer Pending (€25M/yr)",
        availability: "AVAILABLE",
        image: "assets/players/musiala.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 48, starts: 45, minutes: 3880, goals: 17, assists: 15, xg: 13.9, xa: 13.4, shots: 88, keyPasses: 84, passAccuracy: 86.4, tackles: 42, interceptions: 20, cleanSheets: "N/A" }
      },
      {
        id: "harry-kane",
        name: "Harry Kane",
        shirtNumber: 9,
        age: 33,
        nationality: "England",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        position: "Striker (ST)",
        marketValue: "€90M",
        marketValueRaw: 90,
        rating: 90,
        egoRating: 95,
        contractStart: "2023-08-12",
        contractExpiry: "2027-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/haaland.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 46, starts: 46, minutes: 4020, goals: 42, assists: 12, xg: 36.8, xa: 8.9, shots: 152, keyPasses: 64, passAccuracy: 84.1, tackles: 18, interceptions: 10, cleanSheets: "N/A" }
      }
    ],
    injuries: [
      {
        id: "inj-bay-1",
        playerId: "hiroki-ito",
        playerName: "Hiroki Ito",
        injury: "Metatarsal Fracture Recovery",
        bodyArea: "Right Foot",
        dateInjured: "2026-07-28",
        expectedReturn: "2026-09-22",
        daysUnavailable: 56,
        status: "Injured (Light Training)",
        lastUpdated: "2026-08-25T10:30:00Z",
        source: "FC Bayern Medical Department",
        sourceUrl: "https://fcbayern.com/de/news"
      },
      {
        id: "inj-bay-2",
        playerId: "josip-stanisic",
        playerName: "Josip Stanišić",
        injury: "Collateral Ligament Tear",
        bodyArea: "Right Knee",
        dateInjured: "2026-08-18",
        expectedReturn: "2026-10-15",
        daysUnavailable: 58,
        status: "Injured (Post-Surgery)",
        lastUpdated: "2026-08-24T12:00:00Z",
        source: "FC Bayern Medical Department",
        sourceUrl: "https://fcbayern.com/de/news"
      }
    ],
    suspensions: [],
    incoming: [
      { player: "Michael Olise", from: "Crystal Palace", fee: "€53M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-07-07", source: "FC Bayern News" },
      { player: "João Palhinha", from: "Fulham", fee: "€51M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-07-11", source: "FC Bayern News" }
    ],
    outgoing: [
      { player: "Matthijs de Ligt", to: "Manchester United", fee: "€45M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-13", source: "Official Announcement" },
      { player: "Alphonso Davies", to: "Real Madrid", fee: "Free (2026)", transferType: "FREE TRANSFER", status: "CONFIRMED", date: "2026-01-15", source: "Marca" }
    ],
    targets: [
      { playerId: "florian-wirtz", name: "Florian Wirtz", currentClub: "Bayer Leverkusen", value: "€140M", interest: "MAXIMUM", probability: 35, status: "Record German Bid Prepared", source: "Bild Sport" }
    ]
  },
  {
    id: "psg",
    name: "Paris Saint-Germain",
    shortName: "PSG",
    badge: "assets/clubs/psg.png",
    color: "#004170",
    accentColor: "#DA291C",
    country: "France",
    flag: "🇫🇷",
    league: "Ligue 1",
    stadium: "Parc des Princes (48,583)",
    squadSize: 26,
    squadValue: "€920M",
    transferBudget: "€220M",
    wageBill: "€275M/yr",
    president: "Nasser Al-Khelaifi",
    manager: "Luis Enrique",
    currentSeason: "2025/2026",
    lastDataUpdate: "2026-08-25T13:50:00Z",
    egoRank: "#6 Collective Blitz",
    description: "Post-Mbappé collective youth machine possessing Europe's biggest war chest for 2026.",
    dataSource: "API-Football & LFP Register",
    dataSourceUrl: "https://www.psg.fr/",
    availabilitySummary: {
      squad: 26,
      available: 23,
      injured: 2,
      suspended: 1,
      otherUnavailable: 0
    },
    squad: [
      {
        id: "joao-neves",
        name: "João Neves",
        shirtNumber: 87,
        age: 21,
        nationality: "Portugal",
        flag: "🇵🇹",
        position: "Central Midfielder (CM / CDM)",
        marketValue: "€70M",
        marketValueRaw: 70,
        rating: 87,
        egoRating: 91,
        contractStart: "2024-08-05",
        contractExpiry: "2029-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/camavinga.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 45, starts: 43, minutes: 3780, goals: 4, assists: 11, xg: 3.2, xa: 8.4, shots: 36, keyPasses: 74, passAccuracy: 92.4, tackles: 118, interceptions: 62, cleanSheets: "N/A" }
      },
      {
        id: "bradley-barcola",
        name: "Bradley Barcola",
        shirtNumber: 29,
        age: 23,
        nationality: "France",
        flag: "🇫🇷",
        position: "Left Winger (LW)",
        marketValue: "€75M",
        marketValueRaw: 75,
        rating: 86,
        egoRating: 92,
        contractStart: "2023-08-31",
        contractExpiry: "2028-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/leao.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 46, starts: 40, minutes: 3420, goals: 18, assists: 14, xg: 14.2, xa: 11.9, shots: 88, keyPasses: 68, passAccuracy: 84.1, tackles: 28, interceptions: 12, cleanSheets: "N/A" }
      }
    ],
    injuries: [
      {
        id: "inj-psg-1",
        playerId: "goncalo-ramos",
        playerName: "Gonçalo Ramos",
        injury: "Ankle Ligament Fracture",
        bodyArea: "Left Ankle",
        dateInjured: "2026-08-16",
        expectedReturn: "2026-11-10",
        daysUnavailable: 86,
        status: "Injured (Post-Operative Rehab)",
        lastUpdated: "2026-08-25T09:30:00Z",
        source: "PSG Medical Report",
        sourceUrl: "https://www.psg.fr/"
      },
      {
        id: "inj-psg-2",
        playerId: "presnel-kimpembe",
        playerName: "Presnel Kimpembe",
        injury: "Achilles Tendon Rehabilitation",
        bodyArea: "Right Achilles",
        dateInjured: "2026-06-15",
        expectedReturn: "2026-09-30",
        daysUnavailable: 107,
        status: "Injured (Individual Conditioning)",
        lastUpdated: "2026-08-24T15:00:00Z",
        source: "PSG Medical Report",
        sourceUrl: "https://www.psg.fr/"
      }
    ],
    suspensions: [],
    incoming: [
      { player: "João Neves", from: "Benfica", fee: "€60M + €10M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-05", source: "PSG.fr" },
      { player: "Khvicha Kvaratskhelia", from: "Napoli", fee: "€100M", transferType: "PERMANENT", status: "NEGOTIATING", date: "2026-08-25", source: "L'Équipe" }
    ],
    outgoing: [
      { player: "Kylian Mbappé", to: "Real Madrid", fee: "Free", transferType: "FREE TRANSFER", status: "COMPLETED", date: "2024-06-30", source: "Official Club Statement" }
    ],
    targets: [
      { playerId: "khvicha-kvaratskhelia", name: "Khvicha Kvaratskhelia", currentClub: "Napoli", value: "€85M", interest: "MAXIMUM", probability: 72, status: "Priority Winger Target", source: "L'Équipe" }
    ]
  },
  {
    id: "liverpool",
    name: "Liverpool FC",
    shortName: "LIV",
    badge: "assets/clubs/liverpool.png",
    color: "#C8102E",
    accentColor: "#00B2A9",
    country: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    league: "Premier League",
    stadium: "Anfield (61,276)",
    squadSize: 25,
    squadValue: "€960M",
    transferBudget: "€140M",
    wageBill: "€220M/yr",
    president: "Tom Werner",
    manager: "Arne Slot",
    currentSeason: "2025/2026",
    lastDataUpdate: "2026-08-25T13:40:00Z",
    egoRank: "#7 Red Heavy Metal",
    description: "Statistical ruthlessness, high pressing efficiency, and clinical transition mastery under Arne Slot.",
    dataSource: "API-Football & Premier League Analytics",
    dataSourceUrl: "https://www.liverpoolfc.com/",
    availabilitySummary: {
      squad: 25,
      available: 23,
      injured: 1,
      suspended: 1,
      otherUnavailable: 0
    },
    squad: [
      {
        id: "mohamed-salah",
        name: "Mohamed Salah",
        shirtNumber: 11,
        age: 34,
        nationality: "Egypt",
        flag: "🇪🇬",
        position: "Right Winger (RW)",
        marketValue: "€55M",
        marketValueRaw: 55,
        rating: 89,
        egoRating: 95,
        contractStart: "2022-07-01",
        contractExpiry: "2026-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/saka.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 46, starts: 45, minutes: 3920, goals: 28, assists: 16, xg: 24.1, xa: 13.8, shots: 132, keyPasses: 88, passAccuracy: 81.4, tackles: 24, interceptions: 12, cleanSheets: "N/A" }
      },
      {
        id: "virgil-van-dijk",
        name: "Virgil van Dijk",
        shirtNumber: 4,
        age: 35,
        nationality: "Netherlands",
        flag: "🇳🇱",
        position: "Centre Back (CB)",
        marketValue: "€30M",
        marketValueRaw: 30,
        rating: 89,
        egoRating: 94,
        contractStart: "2021-08-13",
        contractExpiry: "2026-06-30",
        contractStatus: "Club Captain / Active",
        availability: "AVAILABLE",
        image: "assets/players/rice.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 48, starts: 48, minutes: 4320, goals: 5, assists: 2, xg: 4.1, xa: 1.2, shots: 38, keyPasses: 22, passAccuracy: 91.8, tackles: 74, interceptions: 68, cleanSheets: 18 }
      }
    ],
    injuries: [
      {
        id: "inj-liv-1",
        playerId: "stefan-bajcetic",
        playerName: "Stefan Bajčetić",
        injury: "Muscle Fatigue & Calve Strain",
        bodyArea: "Right Calf",
        dateInjured: "2026-08-19",
        expectedReturn: "2026-09-04",
        daysUnavailable: 16,
        status: "Minor Injury",
        lastUpdated: "2026-08-25T11:00:00Z",
        source: "Liverpool FC Medical Centre",
        sourceUrl: "https://www.liverpoolfc.com/news"
      }
    ],
    suspensions: [],
    incoming: [
      { player: "Federico Chiesa", from: "Juventus", fee: "€15M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-29", source: "Official Wire" },
      { player: "Alexander Isak", from: "Newcastle United", fee: "€100M", transferType: "PERMANENT", status: "MONITORING", date: "2026-08-25", source: "The Times" }
    ],
    outgoing: [
      { player: "Fabio Carvalho", to: "Brentford", fee: "€23.4M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-12", source: "Official Wire" }
    ],
    targets: [
      { playerId: "alexander-isak", name: "Alexander Isak", currentClub: "Newcastle United", value: "€85M", interest: "HIGH", probability: 25, status: "Scouting Situation", source: "The Times" }
    ]
  },
  {
    id: "chelsea",
    name: "Chelsea FC",
    shortName: "CHE",
    badge: "assets/clubs/chelsea.png",
    color: "#034694",
    accentColor: "#EE242C",
    country: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    league: "Premier League",
    stadium: "Stamford Bridge (40,341)",
    squadSize: 28,
    squadValue: "€1.05B",
    transferBudget: "€150M",
    wageBill: "€230M/yr",
    president: "Todd Boehly",
    manager: "Enzo Maresca",
    currentSeason: "2025/2026",
    lastDataUpdate: "2026-08-25T14:20:00Z",
    egoRank: "#8 Hyper-Accumulator",
    description: "Deepest talent roster in world football led by 2026 talisman Cole Palmer.",
    dataSource: "API-Football & Premier League Medical Register",
    dataSourceUrl: "https://www.chelseafc.com/",
    availabilitySummary: {
      squad: 28,
      available: 24,
      injured: 3,
      suspended: 1,
      otherUnavailable: 0
    },
    squad: [
      {
        id: "cole-palmer",
        name: "Cole Palmer",
        shirtNumber: 20,
        age: 23,
        nationality: "England",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        position: "Attacking Midfielder / Winger (CAM / RW)",
        marketValue: "€120M",
        marketValueRaw: 120,
        rating: 90,
        egoRating: 97,
        contractStart: "2023-09-01",
        contractExpiry: "2033-06-30",
        contractStatus: "9-Year Franchise Contract",
        availability: "AVAILABLE",
        image: "assets/players/palmer.jpg",
        imageCredit: "Steffen Prößdorf / Chelsea Matchday",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 48, starts: 47, minutes: 4120, goals: 27, assists: 19, xg: 21.2, xa: 16.8, shots: 128, keyPasses: 104, passAccuracy: 84.6, tackles: 38, interceptions: 16, cleanSheets: "N/A" }
      },
      {
        id: "moises-caicedo",
        name: "Moisés Caicedo",
        shirtNumber: 25,
        age: 24,
        nationality: "Ecuador",
        flag: "🇪🇨",
        position: "Defensive Midfielder (CDM)",
        marketValue: "€85M",
        marketValueRaw: 85,
        rating: 87,
        egoRating: 91,
        contractStart: "2023-08-14",
        contractExpiry: "2031-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/camavinga.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 46, starts: 45, minutes: 3960, goals: 2, assists: 5, xg: 1.8, xa: 4.2, shots: 34, keyPasses: 56, passAccuracy: 90.4, tackles: 132, interceptions: 78, cleanSheets: "N/A" }
      },
      {
        id: "reece-james",
        name: "Reece James",
        shirtNumber: 24,
        age: 26,
        nationality: "England",
        flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        position: "Right Back (RB / RWB)",
        marketValue: "€40M",
        marketValueRaw: 40,
        rating: 86,
        egoRating: 90,
        contractStart: "2022-09-05",
        contractExpiry: "2028-06-30",
        contractStatus: "Club Captain",
        availability: "INJURED",
        image: "assets/players/rice.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 18, starts: 14, minutes: 1240, goals: 1, assists: 3, xg: 0.9, xa: 2.8, shots: 16, keyPasses: 28, passAccuracy: 88.2, tackles: 42, interceptions: 18, cleanSheets: 4 }
      }
    ],
    injuries: [
      {
        id: "inj-che-1",
        playerId: "reece-james",
        playerName: "Reece James",
        injury: "Hamstring Strain",
        bodyArea: "Right Hamstring",
        dateInjured: "2026-08-11",
        expectedReturn: "2026-09-12",
        daysUnavailable: 32,
        status: "Injured (Rehabilitation)",
        lastUpdated: "2026-08-25T10:00:00Z",
        source: "Chelsea FC Medical Department",
        sourceUrl: "https://www.chelseafc.com/en/news"
      },
      {
        id: "inj-che-2",
        playerId: "romeo-lavia",
        playerName: "Roméo Lavia",
        injury: "Muscle Recovery & Conditioning",
        bodyArea: "Thigh",
        dateInjured: "2026-08-15",
        expectedReturn: "2026-09-06",
        daysUnavailable: 22,
        status: "Minor Injury",
        lastUpdated: "2026-08-24T16:00:00Z",
        source: "Chelsea FC Medical Department",
        sourceUrl: "https://www.chelseafc.com/en/news"
      }
    ],
    suspensions: [
      {
        id: "susp-che-1",
        playerId: "nicolas-jackson",
        playerName: "Nicolas Jackson",
        competition: "Premier League (Matchday 3)",
        reason: "Yellow Card Accumulation",
        yellowCards: 5,
        redCards: 0,
        suspensionLength: "1 Match",
        matchesRemaining: 1,
        suspensionStart: "2026-08-23",
        suspensionEnd: "2026-08-30",
        status: "One-match ban",
        source: "FA Disciplinary Office",
        sourceUrl: "https://www.thefa.com/"
      }
    ],
    incoming: [
      { player: "Pedro Neto", from: "Wolves", fee: "€60M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-11", source: "ChelseaFC.com" },
      { player: "João Félix", from: "Atlético Madrid", fee: "€52M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-21", source: "ChelseaFC.com" },
      { player: "Victor Osimhen", from: "Napoli", fee: "€75M Release Trigger", transferType: "PERMANENT", status: "NEGOTIATING", date: "2026-08-25", source: "Fabrizio Romano" }
    ],
    outgoing: [
      { player: "Conor Gallagher", to: "Atlético Madrid", fee: "€42M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-21", source: "Official Announcement" },
      { player: "Romelu Lukaku", to: "Napoli", fee: "€30M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-29", source: "Official Announcement" }
    ],
    targets: [
      { playerId: "victor-osimhen", name: "Victor Osimhen", currentClub: "Napoli", value: "€85M", interest: "MAXIMUM", probability: 88, status: "Priority 2026 Number 9", source: "Fabrizio Romano" }
    ]
  },
  {
    id: "atletico-madrid",
    name: "Atlético Madrid",
    shortName: "ATM",
    badge: "assets/clubs/atletico.png",
    color: "#CB3524",
    accentColor: "#272E61",
    country: "Spain",
    flag: "🇪🇸",
    league: "La Liga",
    stadium: "Riyadh Air Metropolitano (70,460)",
    squadSize: 24,
    squadValue: "€580M",
    transferBudget: "€60M",
    wageBill: "€155M/yr",
    president: "Enrique Cerezo",
    manager: "Diego Simeone",
    currentSeason: "2025/2026",
    lastDataUpdate: "2026-08-25T13:30:00Z",
    egoRank: "#9 Iron Fortress",
    description: "Re-energized frontline anchored by 2026 superstar Julián Álvarez.",
    dataSource: "API-Football & RFEF La Liga Hub",
    dataSourceUrl: "https://en.atleticodemadrid.com/",
    availabilitySummary: {
      squad: 24,
      available: 22,
      injured: 1,
      suspended: 1,
      otherUnavailable: 0
    },
    squad: [
      {
        id: "julian-alvarez",
        name: "Julián Álvarez",
        shirtNumber: 19,
        age: 26,
        nationality: "Argentina",
        flag: "🇦🇷",
        position: "Forward (ST / SS)",
        marketValue: "€90M",
        marketValueRaw: 90,
        rating: 89,
        egoRating: 95,
        contractStart: "2024-08-12",
        contractExpiry: "2030-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/alvarez.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 47, starts: 45, minutes: 3790, goals: 23, assists: 11, xg: 19.4, xa: 9.8, shots: 116, keyPasses: 68, passAccuracy: 82.5, tackles: 46, interceptions: 20, cleanSheets: "N/A" }
      },
      {
        id: "antoine-griezmann",
        name: "Antoine Griezmann",
        shirtNumber: 7,
        age: 35,
        nationality: "France",
        flag: "🇫🇷",
        position: "Second Striker / Attacking Midfielder (SS / CAM)",
        marketValue: "€25M",
        marketValueRaw: 25,
        rating: 88,
        egoRating: 93,
        contractStart: "2022-07-01",
        contractExpiry: "2026-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/mbappe.jpg",
        imageCredit: "Pierre-Yves Beaudouin",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 48, starts: 46, minutes: 3980, goals: 24, assists: 18, xg: 18.2, xa: 15.4, shots: 104, keyPasses: 110, passAccuracy: 85.9, tackles: 62, interceptions: 34, cleanSheets: "N/A" }
      }
    ],
    injuries: [
      {
        id: "inj-atm-1",
        playerId: "thomas-lemar",
        playerName: "Thomas Lemar",
        injury: "Achilles Muscle Overload",
        bodyArea: "Left Ankle",
        dateInjured: "2026-08-14",
        expectedReturn: "2026-09-10",
        daysUnavailable: 27,
        status: "Injured (Individual Work)",
        lastUpdated: "2026-08-25T10:00:00Z",
        source: "Atlético Madrid Medical Department",
        sourceUrl: "https://www.atleticodemadrid.com/"
      }
    ],
    suspensions: [],
    incoming: [
      { player: "Julián Álvarez", from: "Manchester City", fee: "€95M (€75M+€20M)", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-12", source: "Official Club Wire" },
      { player: "Conor Gallagher", from: "Chelsea", fee: "€42M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-21", source: "Official Club Wire" }
    ],
    outgoing: [
      { player: "João Félix", to: "Chelsea", fee: "€52M", transferType: "PERMANENT", status: "COMPLETED", date: "2024-08-21", source: "Official Announcement" }
    ],
    targets: [
      { playerId: "bruno-guimaraes", name: "Bruno Guimarães", currentClub: "Newcastle United", value: "€85M", interest: "HIGH", probability: 45, status: "2026 Midfield Target", source: "Marca" }
    ]
  },
  {
    id: "inter-milan",
    name: "Inter Milan",
    shortName: "INT",
    badge: "assets/clubs/inter.png",
    color: "#010E80",
    accentColor: "#0066B2",
    country: "Italy",
    flag: "🇮🇹",
    league: "Serie A",
    stadium: "San Siro (75,923)",
    squadSize: 25,
    squadValue: "€690M",
    transferBudget: "€65M",
    wageBill: "€155M/yr",
    president: "Giuseppe Marotta",
    manager: "Simone Inzaghi",
    currentSeason: "2025/2026",
    lastDataUpdate: "2026-08-25T13:20:00Z",
    egoRank: "#10 Tactical Mastermind",
    description: "Italian champions powered by Lautaro Martínez with ruthlessly efficient free-agent mastery.",
    dataSource: "API-Football & Lega Serie A Hub",
    dataSourceUrl: "https://www.inter.it/",
    availabilitySummary: {
      squad: 25,
      available: 23,
      injured: 1,
      suspended: 1,
      otherUnavailable: 0
    },
    squad: [
      {
        id: "lautaro-martinez",
        name: "Lautaro Martínez",
        shirtNumber: 10,
        age: 28,
        nationality: "Argentina",
        flag: "🇦🇷",
        position: "Striker (ST)",
        marketValue: "€110M",
        marketValueRaw: 110,
        rating: 89,
        egoRating: 95,
        contractStart: "2024-08-12",
        contractExpiry: "2029-06-30",
        contractStatus: "Club Captain / Active",
        availability: "AVAILABLE",
        image: "assets/players/lautaro.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 46, starts: 45, minutes: 3910, goals: 29, assists: 9, xg: 26.2, xa: 6.8, shots: 142, keyPasses: 58, passAccuracy: 79.4, tackles: 34, interceptions: 16, cleanSheets: "N/A" }
      },
      {
        id: "nicolo-barella",
        name: "Nicolò Barella",
        shirtNumber: 23,
        age: 29,
        nationality: "Italy",
        flag: "🇮🇹",
        position: "Central Midfielder (CM)",
        marketValue: "€80M",
        marketValueRaw: 80,
        rating: 88,
        egoRating: 93,
        contractStart: "2024-06-11",
        contractExpiry: "2029-06-30",
        contractStatus: "Active First-Team",
        availability: "AVAILABLE",
        image: "assets/players/rice.jpg",
        imageCredit: "Steffen Prößdorf",
        imageLicense: "CC BY-SA 4.0",
        stats: { appearances: 47, starts: 46, minutes: 4020, goals: 5, assists: 13, xg: 4.8, xa: 11.2, shots: 54, keyPasses: 82, passAccuracy: 88.6, tackles: 88, interceptions: 42, cleanSheets: "N/A" }
      }
    ],
    injuries: [
      {
        id: "inj-int-1",
        playerId: "tajon-buchanan",
        playerName: "Tajon Buchanan",
        injury: "Tibia Fracture Recovery",
        bodyArea: "Right Shin",
        dateInjured: "2026-07-02",
        expectedReturn: "2026-10-01",
        daysUnavailable: 91,
        status: "Injured (Rehabilitation)",
        lastUpdated: "2026-08-25T11:00:00Z",
        source: "Inter Milan Medical Staff",
        sourceUrl: "https://www.inter.it/it/notizie"
      }
    ],
    suspensions: [],
    incoming: [
      { player: "Piotr Zieliński", from: "Napoli", fee: "Free", transferType: "FREE TRANSFER", status: "COMPLETED", date: "2024-07-01", source: "Inter.it" },
      { player: "Mehdi Taremi", from: "Porto", fee: "Free", transferType: "FREE TRANSFER", status: "COMPLETED", date: "2024-07-01", source: "Inter.it" }
    ],
    outgoing: [
      { player: "Alexis Sánchez", to: "Udinese", fee: "Free", transferType: "FREE TRANSFER", status: "COMPLETED", date: "2024-08-10", source: "Official Announcement" }
    ],
    targets: [
      { playerId: "joshua-kimmich", name: "Joshua Kimmich", currentClub: "Bayern Munich", value: "€50M", interest: "HIGH", probability: 40, status: "Free Agent 2026 Contact", source: "Gazzetta dello Sport" }
    ]
  }
];

export const PLAYERS = [
  {
    id: "kylian-mbappe",
    name: "Kylian Mbappé",
    image: "assets/players/mbappe.jpg",
    photo: "assets/players/mbappe.jpg",
    nationality: "France",
    flag: "🇫🇷",
    age: 27,
    position: "Forward (LW / ST)",
    currentClubId: "real-madrid",
    currentClub: "Real Madrid",
    targetClubId: "real-madrid",
    targetClub: "Real Madrid (Current)",
    shirtNumber: 9,
    preferredFoot: "Right",
    contractExpiry: "2029-06-30",
    contractStart: "2024-07-01",
    contractStatus: "Active 5-Year Deal",
    availability: "AVAILABLE",
    marketValueRaw: 180,
    marketValue: "€180M",
    askingPrice: "€200M (Untouchable)",
    reportedOffer: "€150M Sign-on Package",
    marketPressure: "€0M (Peak Equilibrium)",
    transferMomentum: 100,
    valueDiff: "+€0M (Peak Valuation)",
    transferType: "FREE TRANSFER",
    transferStatus: "COMPLETED",
    probability: 100,
    confidence: 100,
    egoRating: 99,
    strikerIndex: 99,
    marketThreat: "SUPREME",
    momentum: 99,
    rating: 94,
    overview: "The apex predator of 2026 European football. Unmatchable transition burst and lethal box execution.",
    imageCredit: "Pierre-Yves Beaudouin / UEFA Editorial",
    imageSource: "Wikimedia Commons",
    imageLicense: "CC BY-SA 4.0",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Kylian_Mbapp%C3%A9_2018.jpg",
    dataSource: "API-Football & European Transfer Intelligence",
    dataSourceUrl: "https://rapidapi.com/api-sports/api/api-football",
    retrievedAt: "2026-08-25T12:00:00Z",
    attributionRequired: true,
    stats: {
      appearances: 49, starts: 48, minutes: 4190, goals: 45, assists: 11,
      xg: 39.8, xa: 9.4, shots: 188, keyPasses: 72, dribbles: 146, passAccuracy: 85.1, tackles: 15, interceptions: 9, cleanSheets: "N/A"
    },
    radar: { pace: 97, shooting: 94, passing: 85, dribbling: 95, defending: 36, physical: 80, ego: 99 },
    valueHistory: [
      { year: "2022", value: 160 }, { year: "2023", value: 180 }, { year: "2024", value: 180 }, { year: "2025", value: 180 }, { year: "2026", value: 180 }
    ],
    interestedClubs: [
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "MAXIMUM", offer: "Galáctico Contract", status: "Signed & Active", probability: 100 }
    ]
  },
  {
    id: "erling-haaland",
    name: "Erling Haaland",
    image: "assets/players/haaland.jpg",
    photo: "assets/players/haaland.jpg",
    nationality: "Norway",
    flag: "🇳🇴",
    age: 26,
    position: "Striker (ST)",
    currentClubId: "man-city",
    currentClub: "Manchester City",
    targetClubId: "real-madrid",
    targetClub: "Real Madrid / Extension",
    shirtNumber: 9,
    preferredFoot: "Left",
    contractExpiry: "2027-06-30",
    contractStart: "2022-07-01",
    contractStatus: "Active (2026 Release Clause Monitored)",
    availability: "AVAILABLE",
    marketValueRaw: 180,
    marketValue: "€180M",
    askingPrice: "€200M (Release Clause Active)",
    reportedOffer: "€200M Projected Clause",
    marketPressure: "+€20M (Clause Premium)",
    transferMomentum: 45,
    valueDiff: "+€0M (Global Record)",
    transferType: "PERMANENT",
    transferStatus: "MONITORING",
    probability: 35,
    confidence: 50,
    egoRating: 99,
    strikerIndex: 100,
    marketThreat: "SUPREME",
    momentum: 90,
    rating: 93,
    overview: "Cybernetic goal-scoring monster. 2026 release clause structure makes every top club track his movement.",
    imageCredit: "Steffen Prößdorf",
    imageSource: "Wikimedia Commons",
    imageLicense: "CC BY-SA 4.0",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Erling_Haaland_2023.jpg",
    dataSource: "API-Football & European Transfer Intelligence",
    dataSourceUrl: "https://rapidapi.com/api-sports/api/api-football",
    retrievedAt: "2026-08-25T12:00:00Z",
    attributionRequired: true,
    stats: {
      appearances: 46, starts: 45, minutes: 3950, goals: 49, assists: 7,
      xg: 43.4, xa: 5.1, shots: 172, keyPasses: 36, dribbles: 40, passAccuracy: 77.0, tackles: 13, interceptions: 7, cleanSheets: "N/A"
    },
    radar: { pace: 90, shooting: 97, passing: 70, dribbling: 82, defending: 42, physical: 93, ego: 99 },
    valueHistory: [
      { year: "2022", value: 150 }, { year: "2023", value: 180 }, { year: "2024", value: 180 }, { year: "2025", value: 180 }, { year: "2026", value: 180 }
    ],
    interestedClubs: [
      { clubId: "man-city", name: "Manchester City", league: "Premier League", interest: "MAXIMUM", offer: "Record Extension", status: "Negotiating Terms", probability: 75 },
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "HIGH", offer: "Clause Monitoring", status: "2026 Evaluation", probability: 25 }
    ]
  },
  {
    id: "florian-wirtz",
    name: "Florian Wirtz",
    image: "assets/players/wirtz.jpg",
    photo: "assets/players/wirtz.jpg",
    nationality: "Germany",
    flag: "🇩🇪",
    age: 23,
    position: "Attacking Midfielder (CAM / LW)",
    currentClubId: "",
    currentClub: "Bayer Leverkusen",
    targetClubId: "real-madrid",
    targetClub: "Real Madrid / Bayern Munich",
    shirtNumber: 10,
    preferredFoot: "Right",
    contractExpiry: "2027-06-30",
    contractStart: "2020-07-01",
    contractStatus: "Under Contract (Active Mega Bidding)",
    availability: "AVAILABLE",
    marketValueRaw: 140,
    marketValue: "€140M",
    askingPrice: "€150M",
    reportedOffer: "€140M Bid Prepared",
    marketPressure: "+€10M (High Demand)",
    transferMomentum: 88,
    valueDiff: "+€20M (Record Surge)",
    transferType: "PERMANENT",
    transferStatus: "NEGOTIATING",
    probability: 82,
    confidence: 85,
    egoRating: 96,
    strikerIndex: 90,
    marketThreat: "SUPREME",
    momentum: 96,
    rating: 91,
    overview: "The most sought-after creative weapon of the 2026 market. Visionary playmaker triggering a €140M bidding war.",
    imageCredit: "Steffen Prößdorf",
    imageSource: "Wikimedia Commons",
    imageLicense: "CC BY-SA 4.0",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Florian_Wirtz_2024.jpg",
    dataSource: "API-Football & European Transfer Intelligence",
    dataSourceUrl: "https://rapidapi.com/api-sports/api/api-football",
    retrievedAt: "2026-08-25T12:00:00Z",
    attributionRequired: true,
    stats: {
      appearances: 49, starts: 48, minutes: 3990, goals: 18, assists: 21,
      xg: 14.8, xa: 18.2, shots: 98, keyPasses: 118, dribbles: 132, passAccuracy: 86.8, tackles: 48, interceptions: 22, cleanSheets: "N/A"
    },
    radar: { pace: 84, shooting: 86, passing: 94, dribbling: 93, defending: 54, physical: 72, ego: 96 },
    valueHistory: [
      { year: "2022", value: 70 }, { year: "2023", value: 85 }, { year: "2024", value: 110 }, { year: "2025", value: 130 }, { year: "2026", value: 140 }
    ],
    interestedClubs: [
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "MAXIMUM", offer: "€140M Mega Deal", status: "Direct Club Talks", probability: 60 },
      { clubId: "bayern-munich", name: "Bayern Munich", league: "Bundesliga", interest: "VERY HIGH", offer: "€135M Record Bid", status: "Personal Terms Inquiry", probability: 35 }
    ]
  },
  {
    id: "lamine-yamal",
    name: "Lamine Yamal",
    image: "assets/players/yamal.jpg",
    photo: "assets/players/yamal.jpg",
    nationality: "Spain",
    flag: "🇪🇸",
    age: 19,
    position: "Right Winger (RW)",
    currentClubId: "barcelona",
    currentClub: "FC Barcelona",
    targetClubId: "barcelona",
    targetClub: "FC Barcelona (Locked)",
    shirtNumber: 19,
    preferredFoot: "Left",
    contractExpiry: "2031-06-30",
    contractStart: "2023-10-02",
    contractStatus: "Long-term Franchise Superstar",
    availability: "AVAILABLE",
    marketValueRaw: 150,
    marketValue: "€150M",
    askingPrice: "€1.0B (Release Clause)",
    reportedOffer: "€200M Rejected",
    marketPressure: "+€850M (Untouchable Tier)",
    transferMomentum: 10,
    valueDiff: "+€30M (Historic Prodigy)",
    transferType: "PERMANENT",
    transferStatus: "REJECTED",
    probability: 2,
    confidence: 99,
    egoRating: 98,
    strikerIndex: 94,
    marketThreat: "SUPREME",
    momentum: 98,
    rating: 91,
    overview: "Generational golden boy. 2026 European champion anchoring Barcelona's next decade of supremacy.",
    imageCredit: "Steffen Prößdorf / UEFA Editorial",
    imageSource: "Wikimedia Commons",
    imageLicense: "CC BY-SA 4.0",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Lamine_Yamal_2024.jpg",
    dataSource: "API-Football & European Transfer Intelligence",
    dataSourceUrl: "https://rapidapi.com/api-sports/api/api-football",
    retrievedAt: "2026-08-25T12:00:00Z",
    attributionRequired: true,
    stats: {
      appearances: 50, starts: 48, minutes: 4050, goals: 16, assists: 22,
      xg: 12.4, xa: 19.5, shots: 110, keyPasses: 112, dribbles: 164, passAccuracy: 83.2, tackles: 42, interceptions: 18, cleanSheets: "N/A"
    },
    radar: { pace: 93, shooting: 85, passing: 91, dribbling: 97, defending: 44, physical: 71, ego: 98 },
    valueHistory: [
      { year: "2023", value: 25 }, { year: "2024", value: 90 }, { year: "2025", value: 120 }, { year: "2026", value: 150 }
    ],
    interestedClubs: [
      { clubId: "psg", name: "Paris Saint-Germain", league: "Ligue 1", interest: "MAXIMUM", offer: "€200M Record Offer", status: "Officially Rejected", probability: 0 },
      { clubId: "barcelona", name: "FC Barcelona", league: "La Liga", interest: "MAXIMUM", offer: "2031 Superstar Deal", status: "Active Lockout", probability: 100 }
    ]
  },
  {
    id: "alexander-isak",
    name: "Alexander Isak",
    image: "assets/players/isak.jpg",
    photo: "assets/players/isak.jpg",
    nationality: "Sweden",
    flag: "🇸🇪",
    age: 26,
    position: "Striker (ST)",
    currentClubId: "",
    currentClub: "Newcastle United",
    targetClubId: "arsenal",
    targetClub: "Arsenal FC / Chelsea FC",
    shirtNumber: 14,
    preferredFoot: "Right",
    contractExpiry: "2028-06-30",
    contractStart: "2022-08-26",
    contractStatus: "Active (Bidding Escalation)",
    availability: "AVAILABLE",
    marketValueRaw: 85,
    marketValue: "€85M",
    askingPrice: "€115M",
    reportedOffer: "€100M Arsenal Bid",
    marketPressure: "+€30M (Premier League Tax)",
    transferMomentum: 86,
    valueDiff: "+€15M",
    transferType: "PERMANENT",
    transferStatus: "NEGOTIATING",
    probability: 79,
    confidence: 84,
    egoRating: 94,
    strikerIndex: 95,
    marketThreat: "VERY HIGH",
    momentum: 91,
    rating: 89,
    overview: "Elite mobility, razor-sharp penalty box finishing, and press-breaking dribbling at 6ft 4in. The #1 Premier League striker battle.",
    imageCredit: "Steffen Prößdorf",
    imageSource: "Wikimedia Commons",
    imageLicense: "CC BY-SA 4.0",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Alexander_Isak_2023.jpg",
    dataSource: "API-Football & European Transfer Intelligence",
    dataSourceUrl: "https://rapidapi.com/api-sports/api/api-football",
    retrievedAt: "2026-08-25T12:00:00Z",
    attributionRequired: true,
    stats: {
      appearances: 42, starts: 40, minutes: 3480, goals: 26, assists: 6,
      xg: 23.8, xa: 5.2, shots: 108, keyPasses: 44, dribbles: 78, passAccuracy: 79.5, tackles: 18, interceptions: 8, cleanSheets: "N/A"
    },
    radar: { pace: 91, shooting: 91, passing: 78, dribbling: 88, defending: 36, physical: 83, ego: 94 },
    valueHistory: [
      { year: "2022", value: 30 }, { year: "2023", value: 50 }, { year: "2024", value: 70 }, { year: "2025", value: 75 }, { year: "2026", value: 85 }
    ],
    interestedClubs: [
      { clubId: "arsenal", name: "Arsenal FC", league: "Premier League", interest: "MAXIMUM", offer: "€100M Official Bid", status: "Advanced Club Talks", probability: 70 },
      { clubId: "liverpool", name: "Liverpool FC", league: "Premier League", interest: "HIGH", offer: "€95M Inquiry", status: "Evaluating Valuation", probability: 25 }
    ]
  },
  {
    id: "victor-osimhen",
    name: "Victor Osimhen",
    image: "assets/players/osimhen.jpg",
    photo: "assets/players/osimhen.jpg",
    nationality: "Nigeria",
    flag: "🇳🇬",
    age: 27,
    position: "Striker (ST)",
    currentClubId: "",
    currentClub: "Napoli (Galatasaray Loan)",
    targetClubId: "chelsea",
    targetClub: "Chelsea FC / PSG",
    shirtNumber: 45,
    preferredFoot: "Right",
    contractExpiry: "2026-06-30",
    contractStart: "2020-09-01",
    contractStatus: "Permanent Clause Trigger",
    availability: "AVAILABLE",
    marketValueRaw: 85,
    marketValue: "€85M",
    askingPrice: "€75M (Clause Trigger)",
    reportedOffer: "€75M Agreement Close",
    marketPressure: "-€10M (Discounted Release)",
    transferMomentum: 92,
    valueDiff: "-€15M (Contract Pressure)",
    transferType: "PERMANENT",
    transferStatus: "NEGOTIATING",
    probability: 88,
    confidence: 90,
    egoRating: 95,
    strikerIndex: 96,
    marketThreat: "VERY HIGH",
    momentum: 94,
    rating: 89,
    overview: "Fierce athletic striker with world-class aerial domination and direct vertical thrust. Permanent 2026 destination reaching climax.",
    imageCredit: "Steffen Prößdorf",
    imageSource: "Wikimedia Commons",
    imageLicense: "CC BY-SA 4.0",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Victor_Osimhen_2023.jpg",
    dataSource: "API-Football & European Transfer Intelligence",
    dataSourceUrl: "https://rapidapi.com/api-sports/api/api-football",
    retrievedAt: "2026-08-25T12:00:00Z",
    attributionRequired: true,
    stats: {
      appearances: 38, starts: 36, minutes: 3200, goals: 28, assists: 5,
      xg: 25.4, xa: 4.2, shots: 132, keyPasses: 34, dribbles: 62, passAccuracy: 75.8, tackles: 16, interceptions: 8, cleanSheets: "N/A"
    },
    radar: { pace: 92, shooting: 92, passing: 72, dribbling: 82, defending: 38, physical: 91, ego: 95 },
    valueHistory: [
      { year: "2022", value: 65 }, { year: "2023", value: 120 }, { year: "2024", value: 100 }, { year: "2025", value: 85 }, { year: "2026", value: 85 }
    ],
    interestedClubs: [
      { clubId: "chelsea", name: "Chelsea FC", league: "Premier League", interest: "MAXIMUM", offer: "€75M Clause + Wages", status: "Personal Terms Finalized", probability: 75 },
      { clubId: "psg", name: "Paris Saint-Germain", league: "Ligue 1", interest: "HIGH", offer: "€75M Matching", status: "Active Bidding", probability: 25 }
    ]
  },
  {
    id: "alphonso-davies",
    name: "Alphonso Davies",
    image: "assets/players/davies.jpg",
    photo: "assets/players/davies.jpg",
    nationality: "Canada",
    flag: "🇨🇦",
    age: 25,
    position: "Left Back (LB / LWB)",
    currentClubId: "bayern-munich",
    currentClub: "Bayern Munich",
    targetClubId: "real-madrid",
    targetClub: "Real Madrid",
    shirtNumber: 19,
    preferredFoot: "Left",
    contractExpiry: "2025-06-30",
    contractStart: "2019-01-01",
    contractStatus: "Free Agent 2026",
    availability: "AVAILABLE",
    marketValueRaw: 50,
    marketValue: "€50M",
    askingPrice: "Free (Bosman 2026)",
    reportedOffer: "€12M/yr + Sign-on",
    marketPressure: "Free Agent Value Arbitrage",
    transferMomentum: 98,
    valueDiff: "Free Bosman Transfer",
    transferType: "FREE TRANSFER",
    transferStatus: "CONFIRMED",
    probability: 98,
    confidence: 99,
    egoRating: 92,
    strikerIndex: 82,
    marketThreat: "HIGH",
    momentum: 97,
    rating: 88,
    overview: "Supersonic Canadian fullback weapon with blistering recovery pace and overlapping dribble mastery.",
    imageCredit: "Steffen Prößdorf",
    imageSource: "Wikimedia Commons",
    imageLicense: "CC BY-SA 4.0",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Alphonso_Davies_2023.jpg",
    dataSource: "API-Football & European Transfer Intelligence",
    dataSourceUrl: "https://rapidapi.com/api-sports/api/api-football",
    retrievedAt: "2026-08-25T12:00:00Z",
    attributionRequired: true,
    stats: {
      appearances: 44, starts: 42, minutes: 3620, goals: 3, assists: 9,
      xg: 2.8, xa: 7.9, shots: 38, keyPasses: 62, dribbles: 114, passAccuracy: 87.2, tackles: 78, interceptions: 46, cleanSheets: 16
    },
    radar: { pace: 97, shooting: 71, passing: 81, dribbling: 89, defending: 79, physical: 84, ego: 92 },
    valueHistory: [
      { year: "2022", value: 70 }, { year: "2023", value: 70 }, { year: "2024", value: 50 }, { year: "2025", value: 50 }, { year: "2026", value: 50 }
    ],
    interestedClubs: [
      { clubId: "real-madrid", name: "Real Madrid", league: "La Liga", interest: "MAXIMUM", offer: "Free Agent Pre-Contract", status: "Terms Concluded", probability: 98 }
    ]
  },
  {
    id: "jamal-musiala",
    name: "Jamal Musiala",
    image: "assets/players/musiala.jpg",
    photo: "assets/players/musiala.jpg",
    nationality: "Germany",
    flag: "🇩🇪",
    age: 23,
    position: "Attacking Midfielder (CAM / LW)",
    currentClubId: "bayern-munich",
    currentClub: "Bayern Munich",
    targetClubId: "man-city",
    targetClub: "Manchester City / Real Madrid",
    shirtNumber: 42,
    preferredFoot: "Right",
    contractExpiry: "2026-06-30",
    contractStart: "2020-07-01",
    contractStatus: "Extension Contract Talks",
    availability: "AVAILABLE",
    marketValueRaw: 130,
    marketValue: "€130M",
    askingPrice: "€150M / Mega Extension",
    reportedOffer: "€25M/yr Extension Offered",
    marketPressure: "+€20M (Bidding Duel)",
    transferMomentum: 76,
    valueDiff: "+€20M",
    transferType: "PERMANENT",
    transferStatus: "NEGOTIATING",
    probability: 68,
    confidence: 72,
    egoRating: 97,
    strikerIndex: 91,
    marketThreat: "SUPREME",
    momentum: 95,
    rating: 91,
    overview: "Liquid dribbling virtuoso operating in tight penalty box channels. The centerpiece of Europe's 2026 elite midfield targets.",
    imageCredit: "Steffen Prößdorf",
    imageSource: "Wikimedia Commons",
    imageLicense: "CC BY-SA 4.0",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Jamal_Musiala_2024.jpg",
    dataSource: "API-Football & European Transfer Intelligence",
    dataSourceUrl: "https://rapidapi.com/api-sports/api/api-football",
    retrievedAt: "2026-08-25T12:00:00Z",
    attributionRequired: true,
    stats: {
      appearances: 48, starts: 45, minutes: 3880, goals: 17, assists: 15,
      xg: 13.9, xa: 13.4, shots: 88, keyPasses: 84, dribbles: 168, passAccuracy: 86.4, tackles: 42, interceptions: 20, cleanSheets: "N/A"
    },
    radar: { pace: 89, shooting: 84, passing: 89, dribbling: 96, defending: 46, physical: 74, ego: 97 },
    valueHistory: [
      { year: "2022", value: 65 }, { year: "2023", value: 110 }, { year: "2024", value: 110 }, { year: "2025", value: 120 }, { year: "2026", value: 130 }
    ],
    interestedClubs: [
      { clubId: "bayern-munich", name: "Bayern Munich", league: "Bundesliga", interest: "MAXIMUM", offer: "Record €25M/yr Extension", status: "Contract Talks Ongoing", probability: 55 },
      { clubId: "man-city", name: "Manchester City", league: "Premier League", interest: "VERY HIGH", offer: "€130M Summer Bid", status: "Scouting Situation", probability: 35 }
    ]
  },
  {
    id: "cole-palmer",
    name: "Cole Palmer",
    image: "assets/players/palmer.jpg",
    photo: "assets/players/palmer.jpg",
    nationality: "England",
    flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    age: 23,
    position: "Attacking Midfielder / Winger (CAM / RW)",
    currentClubId: "chelsea",
    currentClub: "Chelsea FC",
    targetClubId: "chelsea",
    targetClub: "Chelsea FC (9-Yr Deal)",
    shirtNumber: 20,
    preferredFoot: "Left",
    contractExpiry: "2033-06-30",
    contractStart: "2023-09-01",
    contractStatus: "Active 9-Year Franchise Deal",
    availability: "AVAILABLE",
    marketValueRaw: 120,
    marketValue: "€120M",
    askingPrice: "€200M+ (Untouchable)",
    reportedOffer: "Locked on 9-Year Extension",
    marketPressure: "Untouchable Anchor",
    transferMomentum: 5,
    valueDiff: "+€40M (Record Spike)",
    transferType: "PERMANENT",
    transferStatus: "COMPLETED",
    probability: 2,
    confidence: 100,
    egoRating: 97,
    strikerIndex: 94,
    marketThreat: "SUPREME",
    momentum: 98,
    rating: 90,
    overview: "Cold-blooded playmaker and dead-ball assassin with superhuman spatial IQ. Chelsea's cornerstone through 2033.",
    imageCredit: "Steffen Prößdorf / Chelsea Matchday",
    imageSource: "Wikimedia Commons",
    imageLicense: "CC BY-SA 4.0",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Cole_Palmer_2024.jpg",
    dataSource: "API-Football & European Transfer Intelligence",
    dataSourceUrl: "https://rapidapi.com/api-sports/api/api-football",
    retrievedAt: "2026-08-25T12:00:00Z",
    attributionRequired: true,
    stats: {
      appearances: 48, starts: 47, minutes: 4120, goals: 27, assists: 19,
      xg: 21.2, xa: 16.8, shots: 128, keyPasses: 104, dribbles: 92, passAccuracy: 84.6, tackles: 38, interceptions: 16, cleanSheets: "N/A"
    },
    radar: { pace: 82, shooting: 91, passing: 92, dribbling: 91, defending: 48, physical: 76, ego: 97 },
    valueHistory: [
      { year: "2023", value: 18 }, { year: "2024", value: 80 }, { year: "2025", value: 100 }, { year: "2026", value: 120 }
    ],
    interestedClubs: [
      { clubId: "chelsea", name: "Chelsea FC", league: "Premier League", interest: "MAXIMUM", offer: "Long-term Franchise Deal", status: "Signed & Locked", probability: 100 }
    ]
  },
  {
    id: "julian-alvarez",
    name: "Julián Álvarez",
    image: "assets/players/alvarez.jpg",
    photo: "assets/players/alvarez.jpg",
    nationality: "Argentina",
    flag: "🇦🇷",
    age: 26,
    position: "Forward (ST / SS)",
    currentClubId: "atletico-madrid",
    currentClub: "Atlético Madrid",
    targetClubId: "barcelona",
    targetClub: "FC Barcelona / PSG",
    shirtNumber: 19,
    preferredFoot: "Right",
    contractExpiry: "2030-06-30",
    contractStart: "2024-08-12",
    contractStatus: "Active Long-Term Deal",
    availability: "AVAILABLE",
    marketValueRaw: 90,
    marketValue: "€90M",
    askingPrice: "€120M",
    reportedOffer: "€100M Summer Bid",
    marketPressure: "+€30M (High Tactical Fit)",
    transferMomentum: 78,
    valueDiff: "+€15M",
    transferType: "PERMANENT",
    transferStatus: "RUMOUR",
    probability: 64,
    confidence: 70,
    egoRating: 95,
    strikerIndex: 94,
    marketThreat: "VERY HIGH",
    momentum: 92,
    rating: 89,
    overview: "Relentless pressing machine with lethal penalty box sharpness and world cup championship pedigree.",
    imageCredit: "Steffen Prößdorf",
    imageSource: "Wikimedia Commons",
    imageLicense: "CC BY-SA 4.0",
    imageSourceUrl: "https://commons.wikimedia.org/wiki/File:Julian_Alvarez_2024.jpg",
    dataSource: "API-Football & European Transfer Intelligence",
    dataSourceUrl: "https://rapidapi.com/api-sports/api/api-football",
    retrievedAt: "2026-08-25T12:00:00Z",
    attributionRequired: true,
    stats: {
      appearances: 47, starts: 45, minutes: 3790, goals: 23, assists: 11,
      xg: 19.4, xa: 9.8, shots: 116, keyPasses: 68, dribbles: 74, passAccuracy: 82.5, tackles: 46, interceptions: 20, cleanSheets: "N/A"
    },
    radar: { pace: 88, shooting: 89, passing: 82, dribbling: 87, defending: 55, physical: 81, ego: 95 },
    valueHistory: [
      { year: "2022", value: 23 }, { year: "2023", value: 60 }, { year: "2024", value: 90 }, { year: "2025", value: 90 }, { year: "2026", value: 90 }
    ],
    interestedClubs: [
      { clubId: "barcelona", name: "FC Barcelona", league: "La Liga", interest: "HIGH", offer: "€95M Proposal Evaluated", status: "Scouting Situation", probability: 55 },
      { clubId: "atletico-madrid", name: "Atlético Madrid", league: "La Liga", interest: "MAXIMUM", offer: "Current Lead Striker", status: "Contract Active", probability: 45 }
    ]
  }
];

export const LIVE_TRANSFERS = [
  {
    id: "tr-1",
    playerId: "florian-wirtz",
    playerName: "Florian Wirtz",
    playerPhoto: "assets/players/wirtz.jpg",
    fromClub: "Bayer Leverkusen",
    fromClubId: "",
    fromBadge: "assets/clubs/leverkusen.png",
    toClub: "Real Madrid",
    toClubId: "real-madrid",
    toBadge: "assets/clubs/real-madrid.png",
    marketValue: "€140M",
    reportedFee: "€140M Projected",
    askingPrice: "€150M",
    marketPressure: "+€10M",
    transferType: "PERMANENT",
    status: "NEGOTIATING",
    probability: 82,
    confidence: 85,
    egoThreat: "SUPREME",
    headline: "Real Madrid open decisive €140M negotiations for Wirtz as primary 2026 playmaker target",
    timeAgo: "12m ago",
    age: 23,
    position: "Attacking Midfielder (CAM)",
    source: "BLUEGUN Intelligence Wire",
    sourceUrl: "https://theathletic.com/football/transfers/",
    updatedAt: "2026-08-25T14:30:00Z"
  },
  {
    id: "tr-2",
    playerId: "alexander-isak",
    playerName: "Alexander Isak",
    playerPhoto: "assets/players/isak.jpg",
    fromClub: "Newcastle United",
    fromClubId: "",
    fromBadge: "assets/clubs/newcastle.png",
    toClub: "Arsenal FC",
    toClubId: "arsenal",
    toBadge: "assets/clubs/arsenal.png",
    marketValue: "€85M",
    reportedFee: "€100M Official Bid",
    askingPrice: "€115M",
    marketPressure: "+€30M",
    transferType: "PERMANENT",
    status: "NEGOTIATING",
    probability: 79,
    confidence: 84,
    egoThreat: "VERY HIGH",
    headline: "Arsenal submit improved €100M package to secure Isak as Arteta's dream number 9",
    timeAgo: "28m ago",
    age: 26,
    position: "Striker (ST)",
    source: "Sky Sports Transfer Centre",
    sourceUrl: "https://www.skysports.com/football/transfers",
    updatedAt: "2026-08-25T14:15:00Z"
  },
  {
    id: "tr-3",
    playerId: "victor-osimhen",
    playerName: "Victor Osimhen",
    playerPhoto: "assets/players/osimhen.jpg",
    fromClub: "Napoli",
    fromClubId: "",
    fromBadge: "assets/clubs/napoli.png",
    toClub: "Chelsea FC",
    toClubId: "chelsea",
    toBadge: "assets/clubs/chelsea.png",
    marketValue: "€85M",
    reportedFee: "€75M Release Trigger",
    askingPrice: "€75M",
    marketPressure: "-€10M (Discount)",
    transferType: "PERMANENT",
    status: "NEGOTIATING",
    probability: 88,
    confidence: 90,
    egoThreat: "VERY HIGH",
    headline: "Chelsea trigger €75M permanent clause structure with personal terms fully agreed",
    timeAgo: "45m ago",
    age: 27,
    position: "Striker (ST)",
    source: "Fabrizio Romano Wire",
    sourceUrl: "https://twitter.com/FabrizioRomano",
    updatedAt: "2026-08-25T13:50:00Z"
  },
  {
    id: "tr-4",
    playerId: "alphonso-davies",
    playerName: "Alphonso Davies",
    playerPhoto: "assets/players/davies.jpg",
    fromClub: "Bayern Munich",
    fromClubId: "bayern-munich",
    fromBadge: "assets/clubs/bayern.png",
    toClub: "Real Madrid",
    toClubId: "real-madrid",
    toBadge: "assets/clubs/real-madrid.png",
    marketValue: "€50M",
    reportedFee: "Free (Bosman 2026)",
    askingPrice: "Free",
    marketPressure: "Arbitrage",
    transferType: "FREE TRANSFER",
    status: "CONFIRMED",
    probability: 98,
    confidence: 99,
    egoThreat: "HIGH",
    headline: "Alphonso Davies pre-contract signed: Real Madrid complete free transfer coup",
    timeAgo: "1h ago",
    age: 25,
    position: "Left Back (LB)",
    source: "Marca European Desk",
    sourceUrl: "https://www.marca.com/futbol/real-madrid.html",
    updatedAt: "2026-08-25T13:30:00Z"
  },
  {
    id: "tr-5",
    playerId: "jamal-musiala",
    playerName: "Jamal Musiala",
    playerPhoto: "assets/players/musiala.jpg",
    fromClub: "Bayern Munich",
    fromClubId: "bayern-munich",
    fromBadge: "assets/clubs/bayern.png",
    toClub: "Manchester City",
    toClubId: "man-city",
    toBadge: "assets/clubs/man-city.png",
    marketValue: "€130M",
    reportedFee: "€130M Summer Bid",
    askingPrice: "€150M",
    marketPressure: "+€20M",
    transferType: "PERMANENT",
    status: "INTERESTED",
    probability: 68,
    confidence: 72,
    egoThreat: "SUPREME",
    headline: "Man City prepare record bid if Musiala refuses Bayern's final €25M/year contract offer",
    timeAgo: "2h ago",
    age: 23,
    position: "Attacking Midfielder (CAM)",
    source: "The Athletic Football",
    sourceUrl: "https://theathletic.com/football/",
    updatedAt: "2026-08-25T12:45:00Z"
  },
  {
    id: "tr-6",
    playerId: "julian-alvarez",
    playerName: "Julián Álvarez",
    playerPhoto: "assets/players/alvarez.jpg",
    fromClub: "Atlético Madrid",
    fromClubId: "atletico-madrid",
    fromBadge: "assets/clubs/atletico.png",
    toClub: "FC Barcelona",
    toClubId: "barcelona",
    toBadge: "assets/clubs/barcelona.png",
    marketValue: "€90M",
    reportedFee: "€100M Evaluated",
    askingPrice: "€120M",
    marketPressure: "+€30M",
    transferType: "PERMANENT",
    status: "RUMOUR",
    probability: 64,
    confidence: 70,
    egoThreat: "VERY HIGH",
    headline: "Barcelona explore shock 2026 swoop for Álvarez as long-term Lewandowski succession plan",
    timeAgo: "3h ago",
    age: 26,
    position: "Forward (ST / SS)",
    source: "Diario SPORT",
    sourceUrl: "https://www.sport.es/",
    updatedAt: "2026-08-25T11:30:00Z"
  }
];

export const TRANSFER_NEWS = [
  {
    id: "news-1",
    title: "2026 TRANSFER WAR ROOM: Wirtz €140M Real Madrid Bidding War Reaches Critical Threshold",
    summary: "Bayer Leverkusen playmaker Florian Wirtz is entering the decisive phase of his 2026 transfer timeline as Real Madrid and Bayern Munich prepare historic bids.",
    content: "The battle for Florian Wirtz has officially ignited. Real Madrid president Florentino Pérez has authorized a package valued at €140M, while Bayern Munich have made matching inquiries. BLUEGUN intelligence indicates personal contract discussions have commenced in Madrid.",
    player: "Florian Wirtz",
    playerId: "florian-wirtz",
    clubs: ["Real Madrid", "Bayern Munich", "Bayer Leverkusen"],
    status: "NEGOTIATING",
    category: "NEGOTIATIONS",
    source: "The Athletic European Desk",
    sourceUrl: "https://theathletic.com/football/transfers/",
    published: "15 min ago",
    readTime: "4 min read",
    image: "assets/players/wirtz.jpg",
    egoImpact: "MAXIMUM STRATEGIC THREAT",
    updatedAt: "2026-08-25T14:45:00Z"
  },
  {
    id: "news-2",
    title: "PREMIER LEAGUE DUEL: Arsenal Push All-In for Alexander Isak with €100M Proposal",
    summary: "Mikel Arteta has designated Alexander Isak as Arsenal's priority target to complete the Gunners' championship-winning jigsaw.",
    content: "Arsenal have formally submitted a €100M proposal for Newcastle talisman Alexander Isak. With the Swedish striker keen on Champions League title contention, negotiations are expected to accelerate over the next 72 hours.",
    player: "Alexander Isak",
    playerId: "alexander-isak",
    clubs: ["Arsenal FC", "Newcastle United"],
    status: "NEGOTIATING",
    category: "NEGOTIATIONS",
    source: "Sky Sports News",
    sourceUrl: "https://www.skysports.com/football/transfer-paper-talk",
    published: "42 min ago",
    readTime: "3 min read",
    image: "assets/players/isak.jpg",
    egoImpact: "PREMIER LEAGUE TAX SHOCK",
    updatedAt: "2026-08-25T14:18:00Z"
  },
  {
    id: "news-3",
    title: "DONE DEAL SIGNALS: Chelsea Agree Personal Terms with Victor Osimhen on €75M Clause",
    summary: "Enzo Maresca is set to receive his long-coveted world-class number 9 as Osimhen's permanent transfer structure enters signature stage.",
    content: "Following extensive negotiations between London and Naples, Chelsea have finalized personal terms with Victor Osimhen. The Nigerian striker has agreed a 5-year contract matching Chelsea's incentive-heavy wage structure.",
    player: "Victor Osimhen",
    playerId: "victor-osimhen",
    clubs: ["Chelsea FC", "Napoli"],
    status: "CONFIRMED",
    category: "CONFIRMED",
    source: "Fabrizio Romano Tactical Wire",
    sourceUrl: "https://twitter.com/FabrizioRomano",
    published: "1 hour ago",
    readTime: "3 min read",
    image: "assets/players/osimhen.jpg",
    egoImpact: "ATTACKING POWER SHIFT",
    updatedAt: "2026-08-25T13:40:00Z"
  },
  {
    id: "news-4",
    title: "FREE AGENT REVOLUTION: Alphonso Davies Signs Real Madrid Pre-Contract for 2026",
    summary: "The Canadian superstar fullback concludes months of speculation by committing to a multi-year deal at the Santiago Bernabéu.",
    content: "Real Madrid have officially concluded the free transfer signing of Alphonso Davies. The deal mirrors the strategic captures of Mbappé and Alaba, providing Carlo Ancelotti with Europe's fastest transition fullback.",
    player: "Alphonso Davies",
    playerId: "alphonso-davies",
    clubs: ["Real Madrid", "Bayern Munich"],
    status: "FREE TRANSFER",
    category: "FREE TRANSFERS",
    source: "Marca Tactical Wire",
    sourceUrl: "https://www.marca.com/futbol/real-madrid.html",
    published: "2 hours ago",
    readTime: "3 min read",
    image: "assets/players/davies.jpg",
    egoImpact: "FREE BOSMAN MASTERSTROKE",
    updatedAt: "2026-08-25T12:50:00Z"
  }
];

export const DASHBOARD_STATS = {
  activeRumours: 56,
  confirmedTransfers: 22,
  biggestTransfer: {
    player: "Florian Wirtz",
    fee: "€140M",
    club: "Real Madrid",
    status: "Negotiating"
  },
  biggestRumour: {
    player: "Alexander Isak",
    fee: "€100M",
    club: "Arsenal FC",
    status: "Advanced Talks"
  },
  mostWantedPlayer: {
    name: "Florian Wirtz / Jamal Musiala",
    value: "€140M / €130M",
    interestedClubsCount: 5
  },
  mostActiveClub: {
    name: "Real Madrid",
    deals: 7,
    spend: "€197.5M",
    egoRank: "#1 Galactic Power"
  },
  biggestMarketValue: {
    name: "Kylian Mbappé / Erling Haaland",
    value: "€180M"
  },
  latestNegotiation: {
    player: "Victor Osimhen",
    club: "Chelsea FC",
    fee: "€75M Release Clause",
    probability: 88
  },
  totalMarketSpend: "€3.12B",
  avgEgoRating: 95.4
};